/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.tec.carpooling.presentation.view;

import java.awt.*;
import java.awt.event.*;
import javax.swing.*;

/**
 *
 * @author hidal
 */
public class AddVehicle extends javax.swing.JFrame {
    private String userRole;
    /**
     * Creates new form AgregarVehiculo
     */
    public AddVehicle(String role) {
        this.userRole = role;
        initComponents();
        getContentPane().add(SideMenu.createToolbar(this, userRole), BorderLayout.WEST);
        // Load the image
        ImageIcon icon = new ImageIcon(getClass().getResource("/Assets/carro.png"));

        // Scale it to fit the label
        Image scaledImage = icon.getImage().getScaledInstance(labelImage.getWidth(), labelImage.getHeight(), Image.SCALE_SMOOTH);

        // Set the scaled image as icon
        labelImage.setIcon(new ImageIcon(scaledImage));
        
        textPlate.addKeyListener(new KeyAdapter() {
            @Override
            public void keyTyped(KeyEvent e) {
                if (textPlate.getText().length() >= 9) {
                    e.consume(); // block the input
                }
            }
        });
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        panelAddVehicle = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        labelAddVehicle = new javax.swing.JLabel();
        buttonAdd = new javax.swing.JButton();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 32767));
        filler2 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 32767));
        panelInfo = new javax.swing.JPanel();
        panelPlate = new javax.swing.JPanel();
        labelPlate = new javax.swing.JLabel();
        textPlate = new javax.swing.JTextField();
        panelCapacity = new javax.swing.JPanel();
        boxCapacity = new javax.swing.JComboBox<>();
        labelCapacity = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        labelImage = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(204, 255, 51));
        setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N

        panelAddVehicle.setLayout(new java.awt.GridLayout(1, 2, 2, 0));

        jPanel1.setBackground(new java.awt.Color(225, 239, 255));
        jPanel1.setLayout(new java.awt.GridBagLayout());

        labelAddVehicle.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 40)); // NOI18N
        labelAddVehicle.setForeground(new java.awt.Color(18, 102, 160));
        labelAddVehicle.setText("ADD VEHICLE");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 12;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(30, 100, 0, 0);
        jPanel1.add(labelAddVehicle, gridBagConstraints);

        buttonAdd.setBackground(new java.awt.Color(246, 172, 30));
        buttonAdd.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        buttonAdd.setForeground(new java.awt.Color(255, 255, 255));
        buttonAdd.setText("Add Vehicle");
        buttonAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAddActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.ipady = 30;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 70);
        jPanel1.add(buttonAdd, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.weighty = 0.1;
        jPanel1.add(filler1, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 20;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.weighty = 0.1;
        jPanel1.add(filler2, gridBagConstraints);

        panelInfo.setBackground(new java.awt.Color(225, 239, 255));
        panelInfo.setMaximumSize(new java.awt.Dimension(394, 60));
        panelInfo.setLayout(new java.awt.GridBagLayout());

        panelPlate.setBackground(new java.awt.Color(225, 239, 255));
        panelPlate.setMaximumSize(new java.awt.Dimension(201, 60));
        panelPlate.setMinimumSize(new java.awt.Dimension(201, 60));
        panelPlate.setPreferredSize(new java.awt.Dimension(193, 60));
        panelPlate.setLayout(new java.awt.GridBagLayout());

        labelPlate.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        labelPlate.setText("<html>Plate Number: <span style='color:red'>*</span></html>");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 30;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 30, 0);
        panelPlate.add(labelPlate, gridBagConstraints);

        textPlate.setMaximumSize(new java.awt.Dimension(64, 22));
        textPlate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textPlateActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 44;
        gridBagConstraints.ipady = 30;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 50, 0);
        panelPlate.add(textPlate, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 20;
        gridBagConstraints.ipady = 10;
        gridBagConstraints.insets = new java.awt.Insets(0, 60, 0, 0);
        panelInfo.add(panelPlate, gridBagConstraints);

        panelCapacity.setBackground(new java.awt.Color(225, 239, 255));
        panelCapacity.setMaximumSize(new java.awt.Dimension(201, 60));
        panelCapacity.setMinimumSize(new java.awt.Dimension(201, 60));
        panelCapacity.setPreferredSize(new java.awt.Dimension(201, 60));
        panelCapacity.setLayout(new java.awt.GridBagLayout());

        boxCapacity.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipady = 10;
        gridBagConstraints.insets = new java.awt.Insets(0, 8, 0, 0);
        panelCapacity.add(boxCapacity, gridBagConstraints);

        labelCapacity.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        labelCapacity.setText("<html>Maximum Capacity: <span style='color:red'>*</span></html>");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 0, 17);
        panelCapacity.add(labelCapacity, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 0, 0);
        panelInfo.add(panelCapacity, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.ipadx = 100;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(100, 0, 0, 0);
        jPanel1.add(panelInfo, gridBagConstraints);

        panelAddVehicle.add(jPanel1);

        jPanel2.setBackground(new java.awt.Color(225, 239, 255));
        jPanel2.setLayout(new java.awt.GridBagLayout());
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 400;
        gridBagConstraints.ipady = 600;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 300, 0);
        jPanel2.add(labelImage, gridBagConstraints);

        panelAddVehicle.add(jPanel2);

        getContentPane().add(panelAddVehicle, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAddActionPerformed
        String plate = textPlate.getText().trim();

        // Check if any field is empty
        if (plate.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Please fill in all required fields.");
            return;
        }
        JOptionPane.showMessageDialog(null, "Vehicle added successfully!");
        // Go back to vehicle registration screen
        javax.swing.SwingUtilities.invokeLater(() -> {
            RegisteredVehicle registry = new RegisteredVehicle(userRole);
            registry.setExtendedState(JFrame.MAXIMIZED_BOTH);
            registry.setVisible(true);

            AddVehicle.this.dispose();
        });
    }//GEN-LAST:event_buttonAddActionPerformed

    private void textPlateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textPlateActionPerformed

    }//GEN-LAST:event_textPlateActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddVehicle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddVehicle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddVehicle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddVehicle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            private String userRole;
            public void run() {
                userRole = "Driver";
                new AddVehicle(userRole).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> boxCapacity;
    private javax.swing.JButton buttonAdd;
    private javax.swing.Box.Filler filler1;
    private javax.swing.Box.Filler filler2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel labelAddVehicle;
    private javax.swing.JLabel labelCapacity;
    private javax.swing.JLabel labelImage;
    private javax.swing.JLabel labelPlate;
    private javax.swing.JPanel panelAddVehicle;
    private javax.swing.JPanel panelCapacity;
    private javax.swing.JPanel panelInfo;
    private javax.swing.JPanel panelPlate;
    private javax.swing.JTextField textPlate;
    // End of variables declaration//GEN-END:variables
}
