/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.tec.carpooling.presentation.view;

import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JScrollPane;
import javax.swing.JTextArea;

import java.awt.Font;
/**
 *
 * @author hidal
 */
public class InitialPage extends javax.swing.JFrame {

    /**
     * Creates new form HomePage
     */
    public InitialPage() {
        initComponents();
        // Load the image
        ImageIcon icon = new ImageIcon(getClass().getResource("/Assets/HomeImage.png"));

        // Scale it to fit the label
        Image scaledImage = icon.getImage().getScaledInstance(jLabelHomeImage.getWidth(), jLabelHomeImage.getHeight(), Image.SCALE_SMOOTH);

        // Set the scaled image as icon
        jLabelHomeImage.setIcon(new ImageIcon(scaledImage));
        
        ImageIcon logo = new ImageIcon(getClass().getResource("/Assets/logoRueda.png"));

        // Scale it to fit the label
        Image scaledLogo = logo.getImage().getScaledInstance(labelLogo.getWidth(), labelLogo.getHeight(), Image.SCALE_SMOOTH);

        // Set the scaled image as icon
        labelLogo.setIcon(new ImageIcon(scaledLogo));
        
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        jLabelHomeImage = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jButtonAboutUs = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jButtonSignUp = new javax.swing.JButton();
        jButtonLogIn = new javax.swing.JButton();
        filler4 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 32767));
        filler5 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 32767));
        labelSlogan = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        labelLogo = new javax.swing.JLabel();
        labelTitulo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(225, 239, 255));
        jPanel1.setLayout(new java.awt.GridBagLayout());

        jLabelHomeImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/HomeImage.png"))); // NOI18N
        jLabelHomeImage.setText("IMAGEN AQUI");
        jLabelHomeImage.setPreferredSize(new java.awt.Dimension(1616, 1100));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.ipadx = -1185;
        gridBagConstraints.ipady = -773;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(22, 0, 20, 200);
        jPanel1.add(jLabelHomeImage, gridBagConstraints);

        jPanel3.setBackground(new java.awt.Color(225, 239, 255));
        jPanel3.setLayout(new java.awt.GridBagLayout());

        jButtonAboutUs.setText("About");
        jButtonAboutUs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAboutUsActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.ipady = 12;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 170, 55, 6);
        jPanel3.add(jButtonAboutUs, gridBagConstraints);

        jPanel2.setBackground(new java.awt.Color(225, 239, 255));
        jPanel2.setLayout(new java.awt.GridBagLayout());

        jButtonSignUp.setBackground(new java.awt.Color(18, 102, 160));
        jButtonSignUp.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButtonSignUp.setForeground(new java.awt.Color(255, 255, 255));
        jButtonSignUp.setText("Register");
        jButtonSignUp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSignUpActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.VERTICAL;
        gridBagConstraints.ipadx = 63;
        gridBagConstraints.ipady = 29;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 10, 0, 50);
        jPanel2.add(jButtonSignUp, gridBagConstraints);

        jButtonLogIn.setBackground(new java.awt.Color(246, 172, 30));
        jButtonLogIn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButtonLogIn.setForeground(new java.awt.Color(255, 255, 255));
        jButtonLogIn.setText("Log In");
        jButtonLogIn.setPreferredSize(new java.awt.Dimension(85, 27));
        jButtonLogIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLogInActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.VERTICAL;
        gridBagConstraints.ipadx = 52;
        gridBagConstraints.ipady = 27;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 50, 0, 10);
        jPanel2.add(jButtonLogIn, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 3;
        jPanel3.add(jPanel2, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 200);
        jPanel1.add(jPanel3, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 200);
        jPanel1.add(filler4, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 9;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.weightx = 0.1;
        jPanel1.add(filler5, gridBagConstraints);

        labelSlogan.setFont(new java.awt.Font("Gadugi", 3, 14)); // NOI18N
        labelSlogan.setForeground(new java.awt.Color(246, 172, 30));
        labelSlogan.setText("Your Carpooling Companion");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 10, 320);
        jPanel1.add(labelSlogan, gridBagConstraints);

        jPanel4.setBackground(new java.awt.Color(225, 239, 255));
        jPanel4.setLayout(new java.awt.GridBagLayout());

        labelLogo.setPreferredSize(new java.awt.Dimension(50, 30));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 33;
        gridBagConstraints.ipady = 59;
        jPanel4.add(labelLogo, gridBagConstraints);

        labelTitulo.setFont(new java.awt.Font("Cascadia Code", 1, 40)); // NOI18N
        labelTitulo.setForeground(new java.awt.Color(18, 102, 160));
        labelTitulo.setText("BUDDYRIDE");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 30);
        jPanel4.add(labelTitulo, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 200);
        jPanel1.add(jPanel4, gridBagConstraints);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonLogInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLogInActionPerformed

        // Mostrar la ventana de inicio de sesión
        //JPanel loginPanel = new LogIn();
        //Main.render_panel(loginPanel);
        
        javax.swing.SwingUtilities.invokeLater(() -> {
            UserLogIn login = new UserLogIn();
            login.setExtendedState(JFrame.MAXIMIZED_BOTH);
            login.setVisible(true);

            this.dispose();
        });

    }//GEN-LAST:event_jButtonLogInActionPerformed

    private void jButtonSignUpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSignUpActionPerformed
        // Mostrar la ventana de inicio de sesión
        //JPanel signupPanel = new SignUp();
        //Main.render_panel(signupPanel);
        
        javax.swing.SwingUtilities.invokeLater(() -> {
            UserSignUp signup = new UserSignUp();
            signup.setExtendedState(JFrame.MAXIMIZED_BOTH);
            signup.setVisible(true);

            this.dispose();
        });
    }//GEN-LAST:event_jButtonSignUpActionPerformed

    private void jButtonAboutUsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAboutUsActionPerformed
        String aboutText = 
        "🚗 About Buddy Ride\n" +
        "\n" +
        "Buddy Ride is your trusted carpooling companion. We connect drivers with empty seats\n" +
        "to passengers heading the same way — making travel smarter, cheaper, and more sustainable.\n" +
        "\n" +
        "Whether you're commuting to work, going to university, or planning a weekend getaway,\n" +
        "Buddy Ride helps you save on costs, reduce traffic, and make new friends along the way.\n" +
        "\n" +
        "🌍 Our Mission:\n" +
        "To make everyday travel more accessible, efficient, and eco-friendly by building a\n" +
        "community of reliable carpoolers who value convenience and safety.\n" +
        "\n" +
        "🤝 How It Works:\n" +
        "- Drivers post trips with stops along the way.\n" +
        "- Passengers search for available rides and choose the best match.\n" +
        "- Everything is coordinated in one place — easy, secure, and community-driven.\n" +
        "\n" +
        "Thank you for choosing Buddy Ride — where every ride has a purpose!";
        
        JFrame about = new JFrame("About Us");
        JTextArea textArea = new JTextArea(aboutText);
        textArea.setFont(new Font("Dialog", Font.PLAIN, 14));
        textArea.setWrapStyleWord(true);
        textArea.setLineWrap(true);
        textArea.setEditable(false);
        about.add(new JScrollPane(textArea));
        about.setSize(400, 300);
        about.setLocationRelativeTo(null);
        about.setVisible(true);
    }//GEN-LAST:event_jButtonAboutUsActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InitialPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InitialPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InitialPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InitialPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InitialPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.Box.Filler filler4;
    private javax.swing.Box.Filler filler5;
    private javax.swing.JButton jButtonAboutUs;
    private javax.swing.JButton jButtonLogIn;
    private javax.swing.JButton jButtonSignUp;
    private javax.swing.JLabel jLabelHomeImage;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JLabel labelLogo;
    private javax.swing.JLabel labelSlogan;
    private javax.swing.JLabel labelTitulo;
    // End of variables declaration//GEN-END:variables
}
