/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.tec.carpooling.presentation.view;

import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author hidal
 */
public class PasswordPage extends javax.swing.JFrame {

    /**
     * Creates new form PasswordPage
     */
    public PasswordPage() {
        initComponents();
        
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel3 = new javax.swing.JPanel();
        labelChangePassword = new javax.swing.JLabel();
        buttonPassword = new javax.swing.JButton();
        panelNew = new javax.swing.JPanel();
        labelNew = new javax.swing.JLabel();
        textNew = new javax.swing.JPasswordField();
        checkNew = new javax.swing.JCheckBox();
        panelOld = new javax.swing.JPanel();
        labelOld = new javax.swing.JLabel();
        textOld = new javax.swing.JPasswordField();
        checkOld = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel3.setBackground(new java.awt.Color(225, 239, 255));
        jPanel3.setLayout(new java.awt.GridBagLayout());

        labelChangePassword.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 40)); // NOI18N
        labelChangePassword.setForeground(new java.awt.Color(18, 102, 160));
        labelChangePassword.setText("PASSWORD");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 40, 0);
        jPanel3.add(labelChangePassword, gridBagConstraints);

        buttonPassword.setBackground(new java.awt.Color(246, 172, 30));
        buttonPassword.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        buttonPassword.setForeground(new java.awt.Color(255, 255, 255));
        buttonPassword.setText("Save Chnages");
        buttonPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonPasswordActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.ipady = 20;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 40, 0);
        jPanel3.add(buttonPassword, gridBagConstraints);

        panelNew.setBackground(new java.awt.Color(225, 239, 255));
        panelNew.setLayout(new java.awt.GridBagLayout());

        labelNew.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        labelNew.setText("<html>New Password: <span style='color:red'>*</span></html>");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 115;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.SOUTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 10, 0);
        panelNew.add(labelNew, gridBagConstraints);

        textNew.setPreferredSize(new java.awt.Dimension(134, 30));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 5, 0);
        panelNew.add(textNew, gridBagConstraints);

        checkNew.setText("Show Password");
        checkNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkNewActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 16;
        panelNew.add(checkNew, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.ipadx = 30;
        gridBagConstraints.ipady = 10;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 30, 0);
        jPanel3.add(panelNew, gridBagConstraints);

        panelOld.setBackground(new java.awt.Color(225, 239, 255));
        panelOld.setLayout(new java.awt.GridBagLayout());

        labelOld.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        labelOld.setText("<html>Previous Password: <span style='color:red'>*</span></html>");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 115;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.SOUTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 10, 0);
        panelOld.add(labelOld, gridBagConstraints);

        textOld.setPreferredSize(new java.awt.Dimension(134, 30));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 5, 0);
        panelOld.add(textOld, gridBagConstraints);

        checkOld.setText("Show Password");
        checkOld.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkOldActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 16;
        panelOld.add(checkOld, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.ipadx = 5;
        gridBagConstraints.ipady = 10;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 30, 0);
        jPanel3.add(panelOld, gridBagConstraints);

        getContentPane().add(jPanel3, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonPasswordActionPerformed
        char[] passwordCharsNew = textNew.getPassword();
        String newP = new String(passwordCharsNew).trim();
        char[] passwordCharsOld = textOld.getPassword();
        String oldP = new String(passwordCharsOld).trim();

        // Check if any field is empty
        if (newP.isEmpty() || oldP.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Please fill in all required fields.");
            return;
        }
        JOptionPane.showMessageDialog(null, "Changes saved successfully!");
        // Go back to User Profile screen
        this.dispose();
    }//GEN-LAST:event_buttonPasswordActionPerformed

    private void checkNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkNewActionPerformed
        if (checkNew.isSelected()) {
            textNew.setEchoChar((char) 0); // Show characters
        } else {
            textNew.setEchoChar('*'); // Hide with asterisks again
        }
    }//GEN-LAST:event_checkNewActionPerformed

    private void checkOldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkOldActionPerformed
        if (checkOld.isSelected()) {
            textOld.setEchoChar((char) 0); // Show characters
        } else {
            textOld.setEchoChar('*'); // Hide with asterisks again
        }
    }//GEN-LAST:event_checkOldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PasswordPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PasswordPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PasswordPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PasswordPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PasswordPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonPassword;
    private javax.swing.JCheckBox checkNew;
    private javax.swing.JCheckBox checkOld;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel labelChangePassword;
    private javax.swing.JLabel labelNew;
    private javax.swing.JLabel labelOld;
    private javax.swing.JPanel panelNew;
    private javax.swing.JPanel panelOld;
    private javax.swing.JPasswordField textNew;
    private javax.swing.JPasswordField textOld;
    // End of variables declaration//GEN-END:variables
}
