/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.tec.carpooling.presentation.view;

import com.tec.carpooling.domain.entity.TripDetails;

import java.awt.Color;
import java.awt.Cursor;
import java.awt.Dimension;
import java.awt.FlowLayout;
import java.awt.Font;
import java.util.ArrayList;
import java.util.List;
import javax.swing.BorderFactory;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.DefaultListModel;
import java.sql.Date;
import java.math.BigDecimal;
/**
 *
 * @author hidal
 */
public class TripInfo extends javax.swing.JFrame {

    /**
     * Creates new form TripInfo
     */
    public TripInfo(TripDetails tripDetails) {
        initComponents();
        setSize(800, 700);
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);

        // Set values in your labels using tripDetails
        labelDateTrip.setText(tripDetails.getTripDate().toString());
        labelStartTime.setText(tripDetails.getStartTime().toString());
        labelEndTime.setText(tripDetails.getEndTime().toString());
        labelPlate.setText(tripDetails.getPlate());
        labelCurrentStatus.setText(tripDetails.getStatus());
        labelSeatAmount.setText(String.valueOf(tripDetails.getMaxSeats()));
        labelAvailableSeats.setText(String.valueOf(tripDetails.getChosenSeats()));
        labelName.setText(tripDetails.getDriverName());
        labelGender.setText(tripDetails.getGender());
        labelAge.setText(String.valueOf(tripDetails.getAge()));
        labelPricePay.setText(tripDetails.getPricePerPassenger() + "");
        labelCurrencyChosen.setText(tripDetails.getCurrencyName());
        // Set full location names
        labelStartName.setText(tripDetails.getStartLocation());
        labelEndName.setText(tripDetails.getEndLocation());

        // Populate phone number list
        DefaultListModel<String> phoneModel = new DefaultListModel<>();
        for (String phone : tripDetails.getDriverPhones()) {
            phoneModel.addElement(phone);
        }
        listNumbers.setModel(phoneModel);

        // Show coordinates
        showCoordinatesList(tripDetails.getCoordinates());
    }
    
    private void showCoordinatesList(List<double[]> coordenates) {
        panelList.removeAll();  // Limpia lista anterior (panel dentro de scroll)

        for (double[] coord : coordenates) {
            double lat = coord[0];
            double lon = coord[1];

            JPanel fila = new JPanel(new FlowLayout(FlowLayout.LEFT));
            fila.setMaximumSize(new Dimension(Integer.MAX_VALUE, 30));
            fila.setBackground(new Color(245, 245, 245));
            fila.setOpaque(true);

            JLabel lbl = new JLabel(String.format("Lat: %.5f, Lon: %.5f", lat, lon));

            JButton btnPin = new JButton("📍");
            btnPin.setBorder(BorderFactory.createEmptyBorder());
            btnPin.setContentAreaFilled(false);
            btnPin.setForeground(Color.BLUE);
            btnPin.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));

            btnPin.addActionListener(e -> {
                new MapViewer(lat, lon).setVisible(true);
            });
            
            btnPin.setFont(new Font("Dialog", Font.PLAIN, 12)); // Windows
            fila.add(btnPin);
            fila.add(lbl);
            panelList.add(fila);
        }

        panelList.revalidate();
        panelList.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        panelTripInfo = new javax.swing.JPanel();
        labelTripInfo = new javax.swing.JLabel();
        verticalDivision = new javax.swing.JPanel();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 32767));
        filler2 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 32767));
        panelRight = new javax.swing.JPanel();
        panelDownR = new javax.swing.JPanel();
        labelTitleRoute = new javax.swing.JLabel();
        panelStops = new javax.swing.JPanel();
        labelStops = new javax.swing.JLabel();
        scrollStops = new javax.swing.JScrollPane();
        panelList = new javax.swing.JPanel();
        panelStartPoint = new javax.swing.JPanel();
        labelStartName = new javax.swing.JLabel();
        labelStartPoint = new javax.swing.JLabel();
        panelEndPoint = new javax.swing.JPanel();
        labelEndName = new javax.swing.JLabel();
        labelEndPoint = new javax.swing.JLabel();
        PanelTopR = new javax.swing.JPanel();
        rightHorizontalDivision = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        panelPrices = new javax.swing.JPanel();
        panelPayment = new javax.swing.JPanel();
        panelPrice = new javax.swing.JPanel();
        labelPrice = new javax.swing.JLabel();
        labelPricePay = new javax.swing.JLabel();
        panelCurrency = new javax.swing.JPanel();
        labelCurrencyChosen = new javax.swing.JLabel();
        labelCurrency = new javax.swing.JLabel();
        labelTitlePricing = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        panelLeft = new javax.swing.JPanel();
        panelTopL = new javax.swing.JPanel();
        leftBottomHorizontalDivision = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        panelTimesDates = new javax.swing.JPanel();
        panelEndTime = new javax.swing.JPanel();
        labelEnd = new javax.swing.JLabel();
        labelEndTime = new javax.swing.JLabel();
        panelDate = new javax.swing.JPanel();
        labelDateTrip = new javax.swing.JLabel();
        labelDate = new javax.swing.JLabel();
        panelStartTime = new javax.swing.JPanel();
        labelStart = new javax.swing.JLabel();
        labelStartTime = new javax.swing.JLabel();
        panelStatus = new javax.swing.JPanel();
        labelStatus = new javax.swing.JLabel();
        labelCurrentStatus = new javax.swing.JLabel();
        labelTitleTime = new javax.swing.JLabel();
        panelMiddleL = new javax.swing.JPanel();
        leftHorizontalDivision = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        panelVehicle = new javax.swing.JPanel();
        panelAmountSeats = new javax.swing.JPanel();
        labelMaxSeats = new javax.swing.JLabel();
        labelSeatAmount = new javax.swing.JLabel();
        panelSeatsLeft = new javax.swing.JPanel();
        labelAvailableSeats = new javax.swing.JLabel();
        labelSeatsLeft = new javax.swing.JLabel();
        panelPlate = new javax.swing.JPanel();
        labelPlateNumber = new javax.swing.JLabel();
        labelPlate = new javax.swing.JLabel();
        labelTitleVehicle = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        labelDriver = new javax.swing.JLabel();
        panelDriver = new javax.swing.JPanel();
        labelNameDriver = new javax.swing.JLabel();
        labelName = new javax.swing.JLabel();
        scrollNumbers = new javax.swing.JScrollPane();
        listNumbers = new javax.swing.JList<>();
        labelGenderDriver = new javax.swing.JLabel();
        labelGender = new javax.swing.JLabel();
        labelAgeDriver = new javax.swing.JLabel();
        labelAge = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        photoDriver = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panelTripInfo.setBackground(new java.awt.Color(225, 239, 255));
        panelTripInfo.setLayout(new java.awt.GridBagLayout());

        labelTripInfo.setFont(new java.awt.Font("Segoe UI Semibold", 1, 40)); // NOI18N
        labelTripInfo.setForeground(new java.awt.Color(18, 102, 160));
        labelTripInfo.setText("TRIP INFORMATION");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(0, 118, 0, 0);
        panelTripInfo.add(labelTripInfo, gridBagConstraints);

        verticalDivision.setBackground(new java.awt.Color(18, 102, 160));

        javax.swing.GroupLayout verticalDivisionLayout = new javax.swing.GroupLayout(verticalDivision);
        verticalDivision.setLayout(verticalDivisionLayout);
        verticalDivisionLayout.setHorizontalGroup(
            verticalDivisionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        verticalDivisionLayout.setVerticalGroup(
            verticalDivisionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridheight = 11;
        gridBagConstraints.fill = java.awt.GridBagConstraints.VERTICAL;
        gridBagConstraints.ipadx = 2;
        gridBagConstraints.insets = new java.awt.Insets(0, 50, 0, 50);
        panelTripInfo.add(verticalDivision, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 13;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.weighty = 0.1;
        panelTripInfo.add(filler1, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.weighty = 0.1;
        panelTripInfo.add(filler2, gridBagConstraints);

        panelRight.setBackground(new java.awt.Color(225, 239, 255));
        panelRight.setLayout(new java.awt.GridBagLayout());

        panelDownR.setBackground(new java.awt.Color(225, 239, 255));
        panelDownR.setLayout(new java.awt.GridBagLayout());

        labelTitleRoute.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        labelTitleRoute.setText("Route");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(0, 20, 20, 0);
        panelDownR.add(labelTitleRoute, gridBagConstraints);

        panelStops.setBackground(new java.awt.Color(225, 239, 255));
        panelStops.setLayout(new java.awt.GridBagLayout());

        labelStops.setText("Stops:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 5, 0);
        panelStops.add(labelStops, gridBagConstraints);

        scrollStops.setBackground(new java.awt.Color(225, 239, 255));

        panelList.setBackground(new java.awt.Color(225, 239, 255));
        panelList.setLayout(new javax.swing.BoxLayout(panelList, javax.swing.BoxLayout.Y_AXIS));
        scrollStops.setViewportView(panelList);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 130;
        gridBagConstraints.ipady = 178;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 10, 0);
        panelStops.add(scrollStops, gridBagConstraints);

        panelStartPoint.setBackground(new java.awt.Color(225, 239, 255));
        panelStartPoint.setLayout(new java.awt.GridBagLayout());

        labelStartName.setText("jLabel18");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 10, 0);
        panelStartPoint.add(labelStartName, gridBagConstraints);

        labelStartPoint.setText("Start: ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 10, 0);
        panelStartPoint.add(labelStartPoint, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        panelStops.add(panelStartPoint, gridBagConstraints);

        panelEndPoint.setBackground(new java.awt.Color(225, 239, 255));
        panelEndPoint.setLayout(new java.awt.GridBagLayout());

        labelEndName.setText("jLabel21");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 10, 0);
        panelEndPoint.add(labelEndName, gridBagConstraints);

        labelEndPoint.setText("End: ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 10, 0);
        panelEndPoint.add(labelEndPoint, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 3;
        panelStops.add(panelEndPoint, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.insets = new java.awt.Insets(0, 20, 0, 0);
        panelDownR.add(panelStops, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        panelRight.add(panelDownR, gridBagConstraints);

        PanelTopR.setBackground(new java.awt.Color(225, 239, 255));
        PanelTopR.setLayout(new java.awt.GridBagLayout());

        rightHorizontalDivision.setBackground(new java.awt.Color(18, 102, 160));

        javax.swing.GroupLayout rightHorizontalDivisionLayout = new javax.swing.GroupLayout(rightHorizontalDivision);
        rightHorizontalDivision.setLayout(rightHorizontalDivisionLayout);
        rightHorizontalDivisionLayout.setHorizontalGroup(
            rightHorizontalDivisionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        rightHorizontalDivisionLayout.setVerticalGroup(
            rightHorizontalDivisionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipady = 2;
        gridBagConstraints.insets = new java.awt.Insets(30, 0, 30, 0);
        PanelTopR.add(rightHorizontalDivision, gridBagConstraints);

        jPanel2.setBackground(new java.awt.Color(225, 239, 255));
        jPanel2.setLayout(new java.awt.GridBagLayout());

        panelPrices.setBackground(new java.awt.Color(225, 239, 255));
        panelPrices.setLayout(new java.awt.GridBagLayout());

        panelPayment.setBackground(new java.awt.Color(225, 239, 255));
        panelPayment.setLayout(new java.awt.GridBagLayout());
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.FIRST_LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 0, 0);
        panelPrices.add(panelPayment, gridBagConstraints);

        panelPrice.setBackground(new java.awt.Color(225, 239, 255));
        panelPrice.setLayout(new java.awt.GridBagLayout());

        labelPrice.setText("Price Per Passenger:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 10);
        panelPrice.add(labelPrice, gridBagConstraints);

        labelPricePay.setText("PricePayed");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        panelPrice.add(labelPricePay, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.FIRST_LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 10, 0);
        panelPrices.add(panelPrice, gridBagConstraints);

        panelCurrency.setBackground(new java.awt.Color(225, 239, 255));
        panelCurrency.setLayout(new java.awt.GridBagLayout());

        labelCurrencyChosen.setText("CurrencyChosen");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        panelCurrency.add(labelCurrencyChosen, gridBagConstraints);

        labelCurrency.setText("Currency:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 10);
        panelCurrency.add(labelCurrency, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.FIRST_LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(0, 53, 10, 0);
        panelPrices.add(panelCurrency, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridheight = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.PAGE_START;
        jPanel2.add(panelPrices, gridBagConstraints);

        labelTitlePricing.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        labelTitlePricing.setText("Pricing");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(0, 20, 20, 0);
        jPanel2.add(labelTitlePricing, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        PanelTopR.add(jPanel2, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        panelRight.add(PanelTopR, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTH;
        panelTripInfo.add(panelRight, gridBagConstraints);

        jPanel5.setBackground(new java.awt.Color(225, 239, 255));
        jPanel5.setLayout(new java.awt.GridBagLayout());

        panelLeft.setBackground(new java.awt.Color(225, 239, 255));
        panelLeft.setLayout(new java.awt.GridBagLayout());

        panelTopL.setBackground(new java.awt.Color(225, 239, 255));
        panelTopL.setLayout(new java.awt.GridBagLayout());

        leftBottomHorizontalDivision.setBackground(new java.awt.Color(18, 102, 160));

        javax.swing.GroupLayout leftBottomHorizontalDivisionLayout = new javax.swing.GroupLayout(leftBottomHorizontalDivision);
        leftBottomHorizontalDivision.setLayout(leftBottomHorizontalDivisionLayout);
        leftBottomHorizontalDivisionLayout.setHorizontalGroup(
            leftBottomHorizontalDivisionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        leftBottomHorizontalDivisionLayout.setVerticalGroup(
            leftBottomHorizontalDivisionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.ipadx = 238;
        gridBagConstraints.ipady = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHEAST;
        gridBagConstraints.insets = new java.awt.Insets(30, 0, 30, 0);
        panelTopL.add(leftBottomHorizontalDivision, gridBagConstraints);

        jPanel1.setBackground(new java.awt.Color(225, 239, 255));
        jPanel1.setLayout(new java.awt.GridBagLayout());

        panelTimesDates.setBackground(new java.awt.Color(225, 239, 255));
        panelTimesDates.setLayout(new java.awt.GridBagLayout());

        panelEndTime.setBackground(new java.awt.Color(225, 239, 255));
        panelEndTime.setLayout(new java.awt.GridBagLayout());

        labelEnd.setText("End Time:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 10;
        panelEndTime.add(labelEnd, gridBagConstraints);

        labelEndTime.setText("EndTIme");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 0;
        panelEndTime.add(labelEndTime, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 52, 10, 0);
        panelTimesDates.add(panelEndTime, gridBagConstraints);

        panelDate.setBackground(new java.awt.Color(225, 239, 255));
        panelDate.setLayout(new java.awt.GridBagLayout());

        labelDateTrip.setText("Date");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        panelDate.add(labelDateTrip, gridBagConstraints);

        labelDate.setText("Date of Trip:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 10;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        panelDate.add(labelDate, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 40, 10, 0);
        panelTimesDates.add(panelDate, gridBagConstraints);

        panelStartTime.setBackground(new java.awt.Color(225, 239, 255));
        panelStartTime.setLayout(new java.awt.GridBagLayout());

        labelStart.setText("Start Time:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 10;
        panelStartTime.add(labelStart, gridBagConstraints);

        labelStartTime.setText("StartTime");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 0;
        panelStartTime.add(labelStartTime, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 49, 10, 0);
        panelTimesDates.add(panelStartTime, gridBagConstraints);

        panelStatus.setBackground(new java.awt.Color(225, 239, 255));
        panelStatus.setLayout(new java.awt.GridBagLayout());

        labelStatus.setText("Current Status:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 10);
        panelStatus.add(labelStatus, gridBagConstraints);

        labelCurrentStatus.setText("Status");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        panelStatus.add(labelCurrentStatus, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.insets = new java.awt.Insets(0, 3, 0, 0);
        panelTimesDates.add(panelStatus, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridheight = 3;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 60);
        jPanel1.add(panelTimesDates, gridBagConstraints);

        labelTitleTime.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        labelTitleTime.setText("Times and Dates");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 20, 0);
        jPanel1.add(labelTitleTime, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        panelTopL.add(jPanel1, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        panelLeft.add(panelTopL, gridBagConstraints);

        panelMiddleL.setBackground(new java.awt.Color(225, 239, 255));
        panelMiddleL.setLayout(new java.awt.GridBagLayout());

        leftHorizontalDivision.setBackground(new java.awt.Color(18, 102, 160));

        javax.swing.GroupLayout leftHorizontalDivisionLayout = new javax.swing.GroupLayout(leftHorizontalDivision);
        leftHorizontalDivision.setLayout(leftHorizontalDivisionLayout);
        leftHorizontalDivisionLayout.setHorizontalGroup(
            leftHorizontalDivisionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        leftHorizontalDivisionLayout.setVerticalGroup(
            leftHorizontalDivisionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.ipadx = 238;
        gridBagConstraints.ipady = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHEAST;
        gridBagConstraints.insets = new java.awt.Insets(30, 0, 30, 0);
        panelMiddleL.add(leftHorizontalDivision, gridBagConstraints);

        jPanel3.setBackground(new java.awt.Color(225, 239, 255));
        jPanel3.setLayout(new java.awt.GridBagLayout());

        panelVehicle.setBackground(new java.awt.Color(225, 239, 255));
        panelVehicle.setLayout(new java.awt.GridBagLayout());

        panelAmountSeats.setBackground(new java.awt.Color(225, 239, 255));
        panelAmountSeats.setLayout(new java.awt.GridBagLayout());

        labelMaxSeats.setText("Amount of Seats:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 10);
        panelAmountSeats.add(labelMaxSeats, gridBagConstraints);

        labelSeatAmount.setText("MaxAmountSeats");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        panelAmountSeats.add(labelSeatAmount, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(0, 23, 10, 0);
        panelVehicle.add(panelAmountSeats, gridBagConstraints);

        panelSeatsLeft.setBackground(new java.awt.Color(225, 239, 255));
        panelSeatsLeft.setLayout(new java.awt.GridBagLayout());

        labelAvailableSeats.setText("NumberSeats");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.PAGE_START;
        panelSeatsLeft.add(labelAvailableSeats, gridBagConstraints);

        labelSeatsLeft.setText("Amount of Seats Left:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.PAGE_START;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 10);
        panelSeatsLeft.add(labelSeatsLeft, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        panelVehicle.add(panelSeatsLeft, gridBagConstraints);

        panelPlate.setBackground(new java.awt.Color(225, 239, 255));
        panelPlate.setLayout(new java.awt.GridBagLayout());

        labelPlateNumber.setText("Plate Number:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 10);
        panelPlate.add(labelPlateNumber, gridBagConstraints);

        labelPlate.setText("PlateNumber");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        panelPlate.add(labelPlate, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(0, 39, 10, 0);
        panelVehicle.add(panelPlate, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridheight = 3;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 20);
        jPanel3.add(panelVehicle, gridBagConstraints);

        labelTitleVehicle.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        labelTitleVehicle.setText("Vehicle");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 20, 0);
        jPanel3.add(labelTitleVehicle, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        panelMiddleL.add(jPanel3, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        panelLeft.add(panelMiddleL, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        jPanel5.add(panelLeft, gridBagConstraints);

        jPanel4.setBackground(new java.awt.Color(225, 239, 255));
        jPanel4.setLayout(new java.awt.GridBagLayout());

        labelDriver.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        labelDriver.setText("Driver");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(0, 20, 20, 0);
        jPanel4.add(labelDriver, gridBagConstraints);

        panelDriver.setBackground(new java.awt.Color(225, 239, 255));
        panelDriver.setLayout(new java.awt.GridBagLayout());

        labelNameDriver.setText("Full Name: ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 10, 5);
        panelDriver.add(labelNameDriver, gridBagConstraints);

        labelName.setText("jLabel3");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 10, 30);
        panelDriver.add(labelName, gridBagConstraints);

        scrollNumbers.setBackground(new java.awt.Color(225, 239, 255));

        scrollNumbers.setViewportView(listNumbers);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipady = 50;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 10, 0);
        panelDriver.add(scrollNumbers, gridBagConstraints);

        labelGenderDriver.setText("Gender: ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 10, 5);
        panelDriver.add(labelGenderDriver, gridBagConstraints);

        labelGender.setText("jLabel5");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 10, 30);
        panelDriver.add(labelGender, gridBagConstraints);

        labelAgeDriver.setText("Age: ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 10, 5);
        panelDriver.add(labelAgeDriver, gridBagConstraints);

        labelAge.setText("jLabel7");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 3;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 10, 30);
        panelDriver.add(labelAge, gridBagConstraints);

        jLabel8.setText("Phone Numbers:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 10, 0);
        panelDriver.add(jLabel8, gridBagConstraints);
        panelDriver.add(photoDriver, new java.awt.GridBagConstraints());

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        jPanel4.add(panelDriver, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTH;
        jPanel5.add(jPanel4, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        panelTripInfo.add(jPanel5, gridBagConstraints);

        getContentPane().add(panelTripInfo, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (Exception ex) {
            ex.printStackTrace();
        }

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            // Mocked trip details for testing
            TripDetails details = new TripDetails();
            details.setTripDate(new java.sql.Date(System.currentTimeMillis()));
            details.setStartTime(java.sql.Timestamp.valueOf("2025-05-20 08:00:00"));
            details.setEndTime(java.sql.Timestamp.valueOf("2025-05-20 09:30:00"));
            details.setPlate("ABC123");
            details.setStatus("Pending");
            details.setChosenSeats(3);
            details.setMaxSeats(5);
            details.setDriverName("Ana González");
            details.setGender("Female");
            details.setAge(28);
            details.setPricePerPassenger(new BigDecimal("3500.00"));
            details.setCurrencyName("CRC");

            // Sample coordinates
            List<double[]> coords = new ArrayList<>();
            coords.add(new double[]{9.9281, -84.0907});
            coords.add(new double[]{10.0021, -84.1111});
            details.setCoordinates(coords);

            // Launch frame
            TripInfo tripFrame = new TripInfo(details);
            tripFrame.setVisible(true);
            tripFrame.setLocationRelativeTo(null); // center on screen
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanelTopR;
    private javax.swing.Box.Filler filler1;
    private javax.swing.Box.Filler filler2;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JLabel labelAge;
    private javax.swing.JLabel labelAgeDriver;
    private javax.swing.JLabel labelAvailableSeats;
    private javax.swing.JLabel labelCurrency;
    private javax.swing.JLabel labelCurrencyChosen;
    private javax.swing.JLabel labelCurrentStatus;
    private javax.swing.JLabel labelDate;
    private javax.swing.JLabel labelDateTrip;
    private javax.swing.JLabel labelDriver;
    private javax.swing.JLabel labelEnd;
    private javax.swing.JLabel labelEndName;
    private javax.swing.JLabel labelEndPoint;
    private javax.swing.JLabel labelEndTime;
    private javax.swing.JLabel labelGender;
    private javax.swing.JLabel labelGenderDriver;
    private javax.swing.JLabel labelMaxSeats;
    private javax.swing.JLabel labelName;
    private javax.swing.JLabel labelNameDriver;
    private javax.swing.JLabel labelPlate;
    private javax.swing.JLabel labelPlateNumber;
    private javax.swing.JLabel labelPrice;
    private javax.swing.JLabel labelPricePay;
    private javax.swing.JLabel labelSeatAmount;
    private javax.swing.JLabel labelSeatsLeft;
    private javax.swing.JLabel labelStart;
    private javax.swing.JLabel labelStartName;
    private javax.swing.JLabel labelStartPoint;
    private javax.swing.JLabel labelStartTime;
    private javax.swing.JLabel labelStatus;
    private javax.swing.JLabel labelStops;
    private javax.swing.JLabel labelTitlePricing;
    private javax.swing.JLabel labelTitleRoute;
    private javax.swing.JLabel labelTitleTime;
    private javax.swing.JLabel labelTitleVehicle;
    private javax.swing.JLabel labelTripInfo;
    private javax.swing.JPanel leftBottomHorizontalDivision;
    private javax.swing.JPanel leftHorizontalDivision;
    private javax.swing.JList<String> listNumbers;
    private javax.swing.JPanel panelAmountSeats;
    private javax.swing.JPanel panelCurrency;
    private javax.swing.JPanel panelDate;
    private javax.swing.JPanel panelDownR;
    private javax.swing.JPanel panelDriver;
    private javax.swing.JPanel panelEndPoint;
    private javax.swing.JPanel panelEndTime;
    private javax.swing.JPanel panelLeft;
    private javax.swing.JPanel panelList;
    private javax.swing.JPanel panelMiddleL;
    private javax.swing.JPanel panelPayment;
    private javax.swing.JPanel panelPlate;
    private javax.swing.JPanel panelPrice;
    private javax.swing.JPanel panelPrices;
    private javax.swing.JPanel panelRight;
    private javax.swing.JPanel panelSeatsLeft;
    private javax.swing.JPanel panelStartPoint;
    private javax.swing.JPanel panelStartTime;
    private javax.swing.JPanel panelStatus;
    private javax.swing.JPanel panelStops;
    private javax.swing.JPanel panelTimesDates;
    private javax.swing.JPanel panelTopL;
    private javax.swing.JPanel panelTripInfo;
    private javax.swing.JPanel panelVehicle;
    private javax.swing.JLabel photoDriver;
    private javax.swing.JPanel rightHorizontalDivision;
    private javax.swing.JScrollPane scrollNumbers;
    private javax.swing.JScrollPane scrollStops;
    private javax.swing.JPanel verticalDivision;
    // End of variables declaration//GEN-END:variables
}
