/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.tec.carpooling.presentation.view;

import com.tec.carpooling.business.service.UserLoginService;
import com.tec.carpooling.business.service.impl.UserLoginServiceImpl;
import com.tec.carpooling.business.service.UserTypeService;
import com.tec.carpooling.business.service.impl.UserTypeServiceImpl;
import com.tec.carpooling.domain.entity.User;
import com.tec.carpooling.presentation.view.admin.AdminFrame;

import javax.swing.JFrame;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

import java.awt.Image;
import java.awt.Color;
import java.awt.Cursor;
import java.awt.event.FocusAdapter;
import java.awt.event.FocusEvent;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.sql.SQLException;

/**
 * Ventana de inicio de sesión para usuarios
 */
public class UserLogIn extends javax.swing.JFrame {
    private final UserLoginService userLoginService;
    private final UserTypeService userTypeService;
    
    /**
     * Constructor de la ventana de inicio de sesión
     */
    public UserLogIn() {
        initComponents();
        userLoginService = new UserLoginServiceImpl();
        userTypeService = new UserTypeServiceImpl();
        
        // Load the image
        ImageIcon icon = new ImageIcon(getClass().getResource("/Assets/calleCarro.png"));

        // Scale it to fit the label
        Image scaledImage = icon.getImage().getScaledInstance(labelImage.getWidth(), labelImage.getHeight(), Image.SCALE_SMOOTH);

        // Set the scaled image as icon
        labelImage.setIcon(new ImageIcon(scaledImage));
        
        // Go to the Register page
        labelRegister.setForeground(Color.BLUE);
        labelRegister.setCursor(new Cursor(Cursor.HAND_CURSOR));
        labelRegister.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {
                javax.swing.SwingUtilities.invokeLater(() -> {
                    UserSignUp signup = new UserSignUp();
                    signup.setExtendedState(JFrame.MAXIMIZED_BOTH);
                    signup.setVisible(true);

                    UserLogIn.this.dispose();
                });
            }
        });
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        panelLogin = new javax.swing.JPanel();
        labelLogIn = new javax.swing.JLabel();
        filler2 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 32767));
        labelImage = new javax.swing.JLabel();
        filler3 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 32767));
        jPanel2 = new javax.swing.JPanel();
        buttonLogin = new javax.swing.JButton();
        labelLog = new javax.swing.JPanel();
        checkPassword = new javax.swing.JCheckBox();
        panelInfo = new javax.swing.JPanel();
        panelPassword = new javax.swing.JPanel();
        textPassword = new javax.swing.JPasswordField();
        labelPassword = new javax.swing.JLabel();
        panelEmail = new javax.swing.JPanel();
        textUsername = new javax.swing.JTextField();
        labelUserName = new javax.swing.JLabel();
        labelRegister = new javax.swing.JLabel();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 32767));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panelLogin.setBackground(new java.awt.Color(225, 239, 255));
        panelLogin.setLayout(new java.awt.GridBagLayout());

        labelLogIn.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 40)); // NOI18N
        labelLogIn.setForeground(new java.awt.Color(18, 102, 160));
        labelLogIn.setText("WELCOME BACK!");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.weightx = 0.1;
        panelLogin.add(labelLogIn, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 18;
        panelLogin.add(filler2, gridBagConstraints);

        labelImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/calleCarroFondoBlanco.png"))); // NOI18N
        labelImage.setMinimumSize(new java.awt.Dimension(450, 450));
        labelImage.setPreferredSize(new java.awt.Dimension(560, 480));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 2;
        panelLogin.add(labelImage, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 24;
        gridBagConstraints.weighty = 0.1;
        panelLogin.add(filler3, gridBagConstraints);

        jPanel2.setBackground(new java.awt.Color(225, 239, 255));
        jPanel2.setLayout(new java.awt.GridBagLayout());

        buttonLogin.setBackground(new java.awt.Color(246, 172, 30));
        buttonLogin.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        buttonLogin.setForeground(new java.awt.Color(255, 255, 255));
        buttonLogin.setText("Log In");
        buttonLogin.setPreferredSize(new java.awt.Dimension(90, 40));
        buttonLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonLoginActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 9;
        gridBagConstraints.ipady = 20;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 20, 0);
        jPanel2.add(buttonLogin, gridBagConstraints);

        labelLog.setBackground(new java.awt.Color(225, 239, 255));
        labelLog.setLayout(new java.awt.GridBagLayout());

        checkPassword.setText("Show Password");
        checkPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkPasswordActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.ipady = 20;
        gridBagConstraints.insets = new java.awt.Insets(5, 0, 0, 0);
        labelLog.add(checkPassword, gridBagConstraints);

        panelInfo.setBackground(new java.awt.Color(225, 239, 255));
        panelInfo.setLayout(new java.awt.GridBagLayout());

        panelPassword.setBackground(new java.awt.Color(225, 239, 255));
        panelPassword.setLayout(new java.awt.GridBagLayout());

        textPassword.setPreferredSize(new java.awt.Dimension(134, 30));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 140;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 5, 0);
        panelPassword.add(textPassword, gridBagConstraints);

        labelPassword.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        labelPassword.setForeground(new java.awt.Color(18, 102, 160));
        labelPassword.setText("Password:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 6;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.insets = new java.awt.Insets(10, 15, 0, 0);
        panelPassword.add(labelPassword, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.gridwidth = 3;
        panelInfo.add(panelPassword, gridBagConstraints);

        panelEmail.setBackground(new java.awt.Color(225, 239, 255));
        panelEmail.setLayout(new java.awt.GridBagLayout());

        textUsername.setPreferredSize(new java.awt.Dimension(135, 30));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 140;
        gridBagConstraints.insets = new java.awt.Insets(0, 7, 10, 0);
        panelEmail.add(textUsername, gridBagConstraints);

        labelUserName.setBackground(new java.awt.Color(18, 102, 160));
        labelUserName.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        labelUserName.setForeground(new java.awt.Color(18, 102, 160));
        labelUserName.setText("Username:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 6;
        gridBagConstraints.insets = new java.awt.Insets(0, 15, 0, 0);
        panelEmail.add(labelUserName, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 0, 0);
        panelInfo.add(panelEmail, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridheight = 6;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        labelLog.add(panelInfo, gridBagConstraints);

        labelRegister.setText("Need to create an account?");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 20, 0);
        labelLog.add(labelRegister, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 9;
        gridBagConstraints.weighty = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 20, 0);
        labelLog.add(filler1, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weighty = 0.1;
        jPanel2.add(labelLog, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weighty = 0.2;
        panelLogin.add(jPanel2, gridBagConstraints);

        getContentPane().add(panelLogin, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonLoginActionPerformed(java.awt.event.ActionEvent evt) {
        // Validar campos requeridos
        if (textUsername.getText().trim().isEmpty() ||
            textPassword.getPassword().length == 0) {
            
            JOptionPane.showMessageDialog(this,
                "Please fill out your username and password.",
                "Places have not been filled in.",
                JOptionPane.WARNING_MESSAGE);
            return;
        }

        try {
            // Intentar iniciar sesión
            User user = userLoginService.login(
                textUsername.getText().trim(),
                new String(textPassword.getPassword()).trim()
            );

            if (user != null) {
                // Verificar si el usuario es administrador
                boolean isAdmin = userTypeService.isAdmin(user.getId());
                
                if (isAdmin) {
                    // Usuario administrador - redirigir a AdminFrame
                    JOptionPane.showMessageDialog(this,
                        "Bienvenido Administrador " + user.getUsername() + "!",
                        "Acceso de Administrador",
                        JOptionPane.INFORMATION_MESSAGE);
                    
                    javax.swing.SwingUtilities.invokeLater(() -> {
                        AdminFrame adminFrame = new AdminFrame();
                        adminFrame.setExtendedState(JFrame.MAXIMIZED_BOTH);
                        adminFrame.setVisible(true);
                        this.dispose();
                    });
                } else {
                    // Usuario regular - redirigir a selección de tipo de usuario
                    JOptionPane.showMessageDialog(this,
                        "Inicio de sesión exitoso.",
                        "Bienvenido",
                        JOptionPane.INFORMATION_MESSAGE);
                    
                    javax.swing.SwingUtilities.invokeLater(() -> {
                        UserType userType = new UserType(user);
                        userType.setExtendedState(JFrame.MAXIMIZED_BOTH);
                        userType.setVisible(true);
                        this.dispose();
                    });
                }
            } else {
                JOptionPane.showMessageDialog(this,
                    "Username or password are incorrect",
                    "Authentitication Error",
                    JOptionPane.ERROR_MESSAGE);
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this,
                "Database Error: " + ex.getMessage(),
                "Connection Error",
                JOptionPane.ERROR_MESSAGE);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this,
                "Unexpected Error: " + ex.getMessage(),
                "Error",
                JOptionPane.ERROR_MESSAGE);
        }
    }

    private void checkPasswordActionPerformed(java.awt.event.ActionEvent evt) {
        if (checkPassword.isSelected()) {
            textPassword.setEchoChar((char) 0); // Show characters
        } else {
            textPassword.setEchoChar('*'); // Hide with asterisks again
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UserLogIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UserLogIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UserLogIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UserLogIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UserLogIn().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonLogin;
    private javax.swing.JCheckBox checkPassword;
    private javax.swing.Box.Filler filler1;
    private javax.swing.Box.Filler filler2;
    private javax.swing.Box.Filler filler3;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel labelImage;
    private javax.swing.JPanel labelLog;
    private javax.swing.JLabel labelLogIn;
    private javax.swing.JLabel labelPassword;
    private javax.swing.JLabel labelRegister;
    private javax.swing.JLabel labelUserName;
    private javax.swing.JPanel panelEmail;
    private javax.swing.JPanel panelInfo;
    private javax.swing.JPanel panelLogin;
    private javax.swing.JPanel panelPassword;
    private javax.swing.JPasswordField textPassword;
    private javax.swing.JTextField textUsername;
    // End of variables declaration//GEN-END:variables
}
