/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import javax.swing.JFrame;
import javax.swing.JToolBar;
import javax.swing.JButton;
import java.awt.BorderLayout;

/**
 *
 * @author hidal
 */
public class AgregarVehiculo extends javax.swing.JFrame {

    /**
     * Creates new form AgregarVehiculo
     */
    public AgregarVehiculo() {
        initComponents();
        JToolBar toolBar = new JToolBar(JToolBar.VERTICAL);
        JButton perfilButton = new JButton("User Profile");
        JButton vehiculoInfoButton = new JButton("Your Vehicle Information");
        JButton agregarVehiculoButton = new JButton("Add a Vehicle");
        JButton agendarViajeButton = new JButton("Schedule a Trip");
        JButton buscarViajesButton = new JButton("Search for Trips");
        JButton historialButton = new JButton("Activity Log");
        JButton adminConsultasButton = new JButton("Queries");
        JButton salirButton = new JButton("Log Out");
        

        // Add to toolbar
        toolBar.add(perfilButton);
        toolBar.add(vehiculoInfoButton);
        toolBar.add(agregarVehiculoButton);
        toolBar.add(agendarViajeButton);
        toolBar.add(buscarViajesButton);
        toolBar.add(historialButton);
        toolBar.add(adminConsultasButton);
        toolBar.add(salirButton);
        getContentPane().add(toolBar, BorderLayout.WEST);
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
        
        perfilButton.addActionListener(e -> {
            javax.swing.SwingUtilities.invokeLater(() -> {
                InfoUsuario profile = new InfoUsuario();
                profile.setExtendedState(JFrame.MAXIMIZED_BOTH);
                profile.setVisible(true);

                this.dispose();
            });
        });

        /*vehiculoInfoButton.addActionListener(e -> {
            javax.swing.SwingUtilities.invokeLater(() -> {
                ModificarPerfil modify = new ModificarPerfil();
                modify.setExtendedState(JFrame.MAXIMIZED_BOTH);
                modify.setVisible(true);

                this.dispose();
            });
        });*/

        agregarVehiculoButton.addActionListener(e -> {
            javax.swing.SwingUtilities.invokeLater(() -> {
                AgregarVehiculo vehicle = new AgregarVehiculo();
                vehicle.setExtendedState(JFrame.MAXIMIZED_BOTH);
                vehicle.setVisible(true);

                this.dispose();
            });
        });

        /*agendarViajeButton.addActionListener(e -> {
            javax.swing.SwingUtilities.invokeLater(() -> {
                ModificarPerfil modify = new ModificarPerfil();
                modify.setExtendedState(JFrame.MAXIMIZED_BOTH);
                modify.setVisible(true);

                this.dispose();
            });
        });*/

        /*buscarViajesButton.addActionListener(e -> {
            javax.swing.SwingUtilities.invokeLater(() -> {
                ModificarPerfil modify = new ModificarPerfil();
                modify.setExtendedState(JFrame.MAXIMIZED_BOTH);
                modify.setVisible(true);

                this.dispose();
            });
        });*/

        /*historialButton.addActionListener(e -> {
            javax.swing.SwingUtilities.invokeLater(() -> {
                ModificarPerfil modify = new ModificarPerfil();
                modify.setExtendedState(JFrame.MAXIMIZED_BOTH);
                modify.setVisible(true);

                this.dispose();
            });
        });*/
        adminConsultasButton.addActionListener(e -> {
            javax.swing.SwingUtilities.invokeLater(() -> {
                ConsultasAdmi queries = new ConsultasAdmi();
                queries.setExtendedState(JFrame.MAXIMIZED_BOTH);
                queries.setVisible(true);

                this.dispose();
            });
        });
        salirButton.addActionListener(e -> {
            javax.swing.SwingUtilities.invokeLater(() -> {
                HomePage home = new HomePage();
                home.setExtendedState(JFrame.MAXIMIZED_BOTH);
                home.setVisible(true);

                this.dispose();
            });
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        panelAgregarVehiculo = new javax.swing.JPanel();
        labelTituloAgregarVehiculo = new javax.swing.JLabel();
        botonAgregarVehiculo = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        labelPlaca = new javax.swing.JLabel();
        textPlaca = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        labelCapacidad = new javax.swing.JLabel();
        boxCapacidad = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(204, 255, 51));
        setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N

        panelAgregarVehiculo.setLayout(new java.awt.GridBagLayout());

        labelTituloAgregarVehiculo.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 30)); // NOI18N
        labelTituloAgregarVehiculo.setText("ADD VEHICLE");
        labelTituloAgregarVehiculo.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        labelTituloAgregarVehiculo.setPreferredSize(new java.awt.Dimension(289, 41));
        labelTituloAgregarVehiculo.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 13;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.VERTICAL;
        gridBagConstraints.weighty = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(7, 100, 0, 0);
        panelAgregarVehiculo.add(labelTituloAgregarVehiculo, gridBagConstraints);

        botonAgregarVehiculo.setBackground(new java.awt.Color(153, 255, 153));
        botonAgregarVehiculo.setText("Agregar Vehículo");
        botonAgregarVehiculo.setPreferredSize(new java.awt.Dimension(123, 40));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.weighty = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(0, 83, 0, 0);
        panelAgregarVehiculo.add(botonAgregarVehiculo, gridBagConstraints);

        jPanel1.setLayout(new java.awt.GridBagLayout());

        labelPlaca.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        labelPlaca.setText("Add the number of your plate:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.insets = new java.awt.Insets(18, 0, 0, 15);
        jPanel1.add(labelPlaca, gridBagConstraints);

        textPlaca.setPreferredSize(new java.awt.Dimension(55, 30));
        textPlaca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textPlacaActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.ipadx = 59;
        gridBagConstraints.insets = new java.awt.Insets(18, 0, 0, 0);
        jPanel1.add(textPlaca, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 6;
        gridBagConstraints.insets = new java.awt.Insets(0, 20, 0, 0);
        panelAgregarVehiculo.add(jPanel1, gridBagConstraints);

        jPanel2.setLayout(new java.awt.GridBagLayout());

        labelCapacidad.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        labelCapacidad.setText("Maximum capacity of Vehicle:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.weighty = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(26, 0, 0, 20);
        jPanel2.add(labelCapacidad, gridBagConstraints);

        boxCapacidad.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(26, 0, 0, 0);
        jPanel2.add(boxCapacidad, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.insets = new java.awt.Insets(0, 20, 0, 0);
        panelAgregarVehiculo.add(jPanel2, gridBagConstraints);

        getContentPane().add(panelAgregarVehiculo, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void textPlacaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textPlacaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textPlacaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AgregarVehiculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AgregarVehiculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AgregarVehiculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AgregarVehiculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AgregarVehiculo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonAgregarVehiculo;
    private javax.swing.JComboBox<String> boxCapacidad;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel labelCapacidad;
    private javax.swing.JLabel labelPlaca;
    private javax.swing.JLabel labelTituloAgregarVehiculo;
    private javax.swing.JPanel panelAgregarVehiculo;
    private javax.swing.JTextField textPlaca;
    // End of variables declaration//GEN-END:variables
}
