/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import javax.swing.JPanel;
import javax.swing.JLabel;
import javax.swing.JButton;
import javax.swing.BorderFactory;
import javax.swing.JOptionPane;
import javax.swing.JFrame;
import javax.swing.BoxLayout;
import java.awt.FlowLayout;
import java.awt.Color;
import java.awt.Insets;
import java.awt.event.ActionListener;
import java.awt.event.ActionEvent;
import java.awt.Dimension;
import java.awt.Component;



/**
 *
 * @author hidal
 */
public class CrearRuta extends javax.swing.JFrame {

    /**
     * Creates new form CrearRuta
     */
    public CrearRuta() {
        initComponents();
        scrollPanelLista.setPreferredSize(new Dimension(200, 200));
        scrollPanelLista.setMaximumSize(new Dimension (200, Integer.MAX_VALUE));
        panelParadas.setLayout(new BoxLayout(panelParadas, BoxLayout.Y_AXIS));
        panelParadas.setMaximumSize(new Dimension (200, Integer.MAX_VALUE));
        panelParadas.setAlignmentX(Component.CENTER_ALIGNMENT);
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
    }
    
    private void agregarParadaVisual(String lat, String lon) {
    JPanel fila = new JPanel(new FlowLayout(FlowLayout.LEFT));
    fila.setMaximumSize(new Dimension(Integer.MAX_VALUE, 25));
    fila.setBackground(new Color(240, 240, 240));
    fila.setOpaque(true);
    
    JLabel lbl = new JLabel("Lat: " + lat + ", Lon: " + lon);
    JButton btnX = new JButton("X");
    
    btnX.setMargin(new Insets(2, 5, 2, 5));
    btnX.setForeground(Color.RED);
    btnX.setBorder(BorderFactory.createEmptyBorder());
    btnX.setContentAreaFilled(false);

    btnX.addActionListener(e -> {
        panelParadas.remove(fila);
        panelParadas.revalidate();
        panelParadas.repaint();
    });

    fila.add(btnX);
    fila.add(lbl);

    panelParadas.add(fila);
    panelParadas.revalidate();
    panelParadas.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        panelCrearViaje = new javax.swing.JPanel();
        labelCrearViaje = new javax.swing.JLabel();
        labelPartida = new javax.swing.JLabel();
        labelPartidaProv = new javax.swing.JLabel();
        labelPartidaCan = new javax.swing.JLabel();
        labelProvinciaDis = new javax.swing.JLabel();
        labelDestino = new javax.swing.JLabel();
        labelDestinoProv = new javax.swing.JLabel();
        labelDestinoCan = new javax.swing.JLabel();
        labelDestinoDis = new javax.swing.JLabel();
        boxPartidaProv = new javax.swing.JComboBox<>();
        boxPartidaCan = new javax.swing.JComboBox<>();
        boxPartidaDis = new javax.swing.JComboBox<>();
        boxDestinoDis = new javax.swing.JComboBox<>();
        boxDestinoCan = new javax.swing.JComboBox<>();
        boxDestinoProv = new javax.swing.JComboBox<>();
        labelParada = new javax.swing.JLabel();
        labelLat = new javax.swing.JLabel();
        labelLon = new javax.swing.JLabel();
        textLat = new javax.swing.JTextField();
        textLon = new javax.swing.JTextField();
        botonAgregarViaje = new javax.swing.JButton();
        botonParada = new javax.swing.JButton();
        scrollPanelLista = new javax.swing.JScrollPane();
        panelParadas = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panelCrearViaje.setLayout(new java.awt.GridBagLayout());

        labelCrearViaje.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 40)); // NOI18N
        labelCrearViaje.setText("CREAR VIAJE");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 9;
        gridBagConstraints.insets = new java.awt.Insets(18, 14, 0, 0);
        panelCrearViaje.add(labelCrearViaje, gridBagConstraints);

        labelPartida.setText("Agregar punto de partida:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.insets = new java.awt.Insets(18, 14, 0, 0);
        panelCrearViaje.add(labelPartida, gridBagConstraints);

        labelPartidaProv.setText("Provincia:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.insets = new java.awt.Insets(10, 34, 0, 0);
        panelCrearViaje.add(labelPartidaProv, gridBagConstraints);

        labelPartidaCan.setText("Cantón:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.gridheight = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(21, 34, 0, 0);
        panelCrearViaje.add(labelPartidaCan, gridBagConstraints);

        labelProvinciaDis.setText("Distrito:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 13;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(9, 35, 0, 0);
        panelCrearViaje.add(labelProvinciaDis, gridBagConstraints);

        labelDestino.setText("Agregar punto de destino:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 15;
        gridBagConstraints.gridwidth = 5;
        gridBagConstraints.insets = new java.awt.Insets(12, 14, 0, 0);
        panelCrearViaje.add(labelDestino, gridBagConstraints);

        labelDestinoProv.setText("Provincia:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 16;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.insets = new java.awt.Insets(9, 34, 0, 0);
        panelCrearViaje.add(labelDestinoProv, gridBagConstraints);

        labelDestinoCan.setText("Cantón:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 18;
        gridBagConstraints.insets = new java.awt.Insets(15, 34, 0, 0);
        panelCrearViaje.add(labelDestinoCan, gridBagConstraints);

        labelDestinoDis.setText("Distrito:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 20;
        gridBagConstraints.insets = new java.awt.Insets(12, 35, 0, 0);
        panelCrearViaje.add(labelDestinoDis, gridBagConstraints);

        boxPartidaProv.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 6;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.insets = new java.awt.Insets(7, 12, 0, 0);
        panelCrearViaje.add(boxPartidaProv, gridBagConstraints);

        boxPartidaCan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.gridwidth = 6;
        gridBagConstraints.gridheight = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 12, 0, 0);
        panelCrearViaje.add(boxPartidaCan, gridBagConstraints);

        boxPartidaDis.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 13;
        gridBagConstraints.gridwidth = 6;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 12, 0, 0);
        panelCrearViaje.add(boxPartidaDis, gridBagConstraints);

        boxDestinoDis.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 20;
        gridBagConstraints.gridwidth = 6;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.insets = new java.awt.Insets(9, 12, 0, 0);
        panelCrearViaje.add(boxDestinoDis, gridBagConstraints);

        boxDestinoCan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 18;
        gridBagConstraints.gridwidth = 6;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.insets = new java.awt.Insets(12, 12, 0, 0);
        panelCrearViaje.add(boxDestinoCan, gridBagConstraints);

        boxDestinoProv.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 16;
        gridBagConstraints.gridwidth = 6;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.insets = new java.awt.Insets(6, 12, 0, 0);
        panelCrearViaje.add(boxDestinoProv, gridBagConstraints);

        labelParada.setText("Agregar puntos de parada:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 17;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 25;
        gridBagConstraints.insets = new java.awt.Insets(18, 6, 0, 0);
        panelCrearViaje.add(labelParada, gridBagConstraints);

        labelLat.setText("Latitud:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 17;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 11;
        gridBagConstraints.insets = new java.awt.Insets(10, 12, 0, 0);
        panelCrearViaje.add(labelLat, gridBagConstraints);

        labelLon.setText("Longitud:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 17;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.gridwidth = 12;
        gridBagConstraints.insets = new java.awt.Insets(9, 12, 0, 0);
        panelCrearViaje.add(labelLon, gridBagConstraints);

        textLat.setPreferredSize(new java.awt.Dimension(80, 25));
        textLat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textLatActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 29;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 27;
        gridBagConstraints.gridheight = 3;
        gridBagConstraints.ipadx = 16;
        gridBagConstraints.ipady = 3;
        gridBagConstraints.insets = new java.awt.Insets(6, 7, 0, 0);
        panelCrearViaje.add(textLat, gridBagConstraints);

        textLon.setPreferredSize(new java.awt.Dimension(80, 25));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 29;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.gridwidth = 26;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 16;
        gridBagConstraints.ipady = 3;
        gridBagConstraints.insets = new java.awt.Insets(5, 6, 0, 0);
        panelCrearViaje.add(textLon, gridBagConstraints);

        botonAgregarViaje.setText("Agregar Viaje");
        botonAgregarViaje.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAgregarViajeActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 8;
        gridBagConstraints.gridy = 22;
        gridBagConstraints.gridwidth = 10;
        gridBagConstraints.insets = new java.awt.Insets(12, 11, 6, 0);
        panelCrearViaje.add(botonAgregarViaje, gridBagConstraints);

        botonParada.setText("Agregar Parada");
        botonParada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonParadaActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 17;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.gridwidth = 13;
        gridBagConstraints.gridheight = 6;
        gridBagConstraints.insets = new java.awt.Insets(6, 16, 0, 0);
        panelCrearViaje.add(botonParada, gridBagConstraints);

        scrollPanelLista.setPreferredSize(new java.awt.Dimension(200, 200));

        panelParadas.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        panelParadas.setLayout(new javax.swing.BoxLayout(panelParadas, javax.swing.BoxLayout.Y_AXIS));
        scrollPanelLista.setViewportView(panelParadas);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 17;
        gridBagConstraints.gridy = 13;
        gridBagConstraints.gridwidth = 40;
        gridBagConstraints.gridheight = 9;
        gridBagConstraints.ipadx = 142;
        gridBagConstraints.ipady = 130;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(3, 12, 0, 0);
        panelCrearViaje.add(scrollPanelLista, gridBagConstraints);

        getContentPane().add(panelCrearViaje, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonAgregarViajeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAgregarViajeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botonAgregarViajeActionPerformed
 
    private void botonParadaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonParadaActionPerformed
        String lat = textLat.getText().trim();
        String lon = textLon.getText().trim();

        if(!lat.isEmpty() && !lon.isEmpty()){
        agregarParadaVisual(lat, lon);
        textLat.setText("");
        textLon.setText("");
        } else{
            JOptionPane.showMessageDialog(this, "Ingrese latitud y longitud.");
        }
    }//GEN-LAST:event_botonParadaActionPerformed

    private void textLatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textLatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textLatActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CrearRuta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CrearRuta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CrearRuta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CrearRuta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CrearRuta().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonAgregarViaje;
    private javax.swing.JButton botonParada;
    private javax.swing.JComboBox<String> boxDestinoCan;
    private javax.swing.JComboBox<String> boxDestinoDis;
    private javax.swing.JComboBox<String> boxDestinoProv;
    private javax.swing.JComboBox<String> boxPartidaCan;
    private javax.swing.JComboBox<String> boxPartidaDis;
    private javax.swing.JComboBox<String> boxPartidaProv;
    private javax.swing.JLabel labelCrearViaje;
    private javax.swing.JLabel labelDestino;
    private javax.swing.JLabel labelDestinoCan;
    private javax.swing.JLabel labelDestinoDis;
    private javax.swing.JLabel labelDestinoProv;
    private javax.swing.JLabel labelLat;
    private javax.swing.JLabel labelLon;
    private javax.swing.JLabel labelParada;
    private javax.swing.JLabel labelPartida;
    private javax.swing.JLabel labelPartidaCan;
    private javax.swing.JLabel labelPartidaProv;
    private javax.swing.JLabel labelProvinciaDis;
    private javax.swing.JPanel panelCrearViaje;
    private javax.swing.JPanel panelParadas;
    private javax.swing.JScrollPane scrollPanelLista;
    private javax.swing.JTextField textLat;
    private javax.swing.JTextField textLon;
    // End of variables declaration//GEN-END:variables
}
