/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import javax.swing.JFrame;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import java.awt.Image;
import java.awt.Color;
import java.awt.event.FocusAdapter;
import java.awt.event.FocusEvent;
import javax.swing.JTextField;

/**
 *
 * @author hidal
 */

public class UserLogIn extends javax.swing.JFrame {
    // Suppose your text field is called 'textCorreo'
    private void setupPlaceholder(JTextField textField, String placeholder) {
        textField.setText(placeholder);
        textField.setForeground(Color.GRAY);

        textField.addFocusListener(new FocusAdapter() {
            @Override
            public void focusGained(FocusEvent e) {
                if (textField.getText().equals(placeholder)) {
                    textField.setText("");
                    textField.setForeground(Color.BLACK);
                }
            }

            @Override
            public void focusLost(FocusEvent e) {
                if (textField.getText().isEmpty()) {
                    textField.setForeground(Color.GRAY);
                    textField.setText(placeholder);
                }
            }
        });
    }
    
    /**
     * Creates new form UserLogIn
     */
    public UserLogIn() {
        initComponents();
        // Load the image
        ImageIcon icon = new ImageIcon(getClass().getResource("/Assets/calleCarro.png"));

        // Scale it to fit the label
        Image scaledImage = icon.getImage().getScaledInstance(labelImage.getWidth(), labelImage.getHeight(), Image.SCALE_SMOOTH);

        // Set the scaled image as icon
        labelImage.setIcon(new ImageIcon(scaledImage));
        setupPlaceholder(textCorreo, "example@domain.com");
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        panelIngreso = new javax.swing.JPanel();
        labelIngresar = new javax.swing.JLabel();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 32767));
        panelContraseña = new javax.swing.JPanel();
        textContraseña = new javax.swing.JPasswordField();
        labelContraseña = new javax.swing.JLabel();
        panelCorreo = new javax.swing.JPanel();
        textCorreo = new javax.swing.JTextField();
        labelCorreo = new javax.swing.JLabel();
        botonIngresar = new javax.swing.JButton();
        filler2 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 32767));
        labelImage = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panelIngreso.setLayout(new java.awt.GridBagLayout());

        labelIngresar.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 40)); // NOI18N
        labelIngresar.setForeground(new java.awt.Color(18, 102, 160));
        labelIngresar.setText("WELCOME BACK!");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.weightx = 0.1;
        panelIngreso.add(labelIngresar, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 16;
        gridBagConstraints.weighty = 0.1;
        panelIngreso.add(filler1, gridBagConstraints);

        panelContraseña.setLayout(new java.awt.GridBagLayout());

        textContraseña.setText("jPasswordField1");
        textContraseña.setPreferredSize(new java.awt.Dimension(134, 30));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 19, 0);
        panelContraseña.add(textContraseña, gridBagConstraints);

        labelContraseña.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        labelContraseña.setForeground(new java.awt.Color(18, 102, 160));
        labelContraseña.setText("Password:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 6;
        panelContraseña.add(labelContraseña, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 15;
        gridBagConstraints.gridwidth = 3;
        panelIngreso.add(panelContraseña, gridBagConstraints);

        panelCorreo.setLayout(new java.awt.GridBagLayout());

        textCorreo.setText("jTextField1");
        textCorreo.setPreferredSize(new java.awt.Dimension(135, 30));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(10, 5, 10, 0);
        panelCorreo.add(textCorreo, gridBagConstraints);

        labelCorreo.setBackground(new java.awt.Color(18, 102, 160));
        labelCorreo.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        labelCorreo.setForeground(new java.awt.Color(18, 102, 160));
        labelCorreo.setText("Email:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 30;
        panelCorreo.add(labelCorreo, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.gridwidth = 3;
        panelIngreso.add(panelCorreo, gridBagConstraints);

        botonIngresar.setBackground(new java.awt.Color(246, 172, 30));
        botonIngresar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        botonIngresar.setForeground(new java.awt.Color(255, 255, 255));
        botonIngresar.setText("Log In");
        botonIngresar.setPreferredSize(new java.awt.Dimension(90, 40));
        botonIngresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonIngresarActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 20;
        gridBagConstraints.weighty = 0.1;
        panelIngreso.add(botonIngresar, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 18;
        panelIngreso.add(filler2, gridBagConstraints);

        labelImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/calleCarroFondoBlanco.png"))); // NOI18N
        labelImage.setText("jLabel1");
        labelImage.setPreferredSize(new java.awt.Dimension(560, 480));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 2;
        panelIngreso.add(labelImage, gridBagConstraints);

        getContentPane().add(panelIngreso, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonIngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonIngresarActionPerformed
        javax.swing.SwingUtilities.invokeLater(() -> {
            InfoUsuario profile = new InfoUsuario();
            profile.setExtendedState(JFrame.MAXIMIZED_BOTH);
            profile.setVisible(true);

            this.dispose();
        });
    }//GEN-LAST:event_botonIngresarActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UserLogIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UserLogIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UserLogIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UserLogIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UserLogIn().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonIngresar;
    private javax.swing.Box.Filler filler1;
    private javax.swing.Box.Filler filler2;
    private javax.swing.JLabel labelContraseña;
    private javax.swing.JLabel labelCorreo;
    private javax.swing.JLabel labelImage;
    private javax.swing.JLabel labelIngresar;
    private javax.swing.JPanel panelContraseña;
    private javax.swing.JPanel panelCorreo;
    private javax.swing.JPanel panelIngreso;
    private javax.swing.JPasswordField textContraseña;
    private javax.swing.JTextField textCorreo;
    // End of variables declaration//GEN-END:variables
}
