name: Keep draw.io export synchronized

on:
  push:
    branches:
      - main
    paths:
      - "**.drawio"
      - .github/workflows/drawio-export.yaml

# Enable write permissions to push changes
permissions:
  contents: write

concurrency:
  group: drawio-export-${{ github.ref }}
  cancel-in-progress: true

jobs:
  drawio-export:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          persist-credentials: true

      - name: Configure Git identity
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"

      # Add the workspace directory as safe for Git
      - name: Add safe directory for Git
        run: git config --global --add safe.directory /github/workspace

      # Export to PNG
      - name: Export draw.io to PNG
        uses: rlespinasse/drawio-export-action@v2
        with:
          path: modelos/IC-4301-Proyecto#1.drawio
          format: png
          transparent: true
          output: export
          action-mode: all

      # Export to PDF
      - name: Export draw.io to PDF
        uses: rlespinasse/drawio-export-action@v2
        with:
          path: modelos/IC-4301-Proyecto#1.drawio
          format: pdf
          transparent: true
          output: export
          action-mode: all
          crop: true

      # Commit the export folder
      - name: Commit export folder
        run: |
          git add modelos/export
          git commit -m "Update draw.io export" || echo "No changes to commit"
          git push origin ${{ github.ref }}

      # Upload the export folder as an artifact
      - name: Upload export artifact
        uses: actions/upload-artifact@v4
        with:
          name: export
          path: modelos/export
