name: Keep draw.io export synchronized

on:
  push:
    branches:
      - main
    paths:
      - "**.drawio"
      - .github/workflows/drawio-export.yaml

concurrency:
  group: drawio-export-${{ github.ref }}
  cancel-in-progress: true

jobs:
  drawio-export:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del repositorio
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

       # Agregar el directorio de trabajo como seguro en Git para evitar advertencias
      - name: Agregar directorio seguro para Git
        run: git config --global --add safe.directory /github/workspace
      
      # Exportar a PNG
      - name: Exportar draw.io a PNG
        uses: rlespinasse/drawio-export-action@v2
        with:
          path: modelos/IC-4301-Proyecto#1.drawio
          format: png
          transparent: true
          output: export
          action-mode: all

      # Exportar a PDF
      - name: Exportar draw.io a PDF
        uses: rlespinasse/drawio-export-action@v2
        with:
          path: modelos/IC-4301-Proyecto#1.drawio
          format: pdf
          transparent: true
          output: export
          action-mode: all

     

      # Commit de la carpeta export
      - name: Commit de la carpeta export
        run: |
          git add modelos/export
          git commit -m "Actualizar export de draw.io" || echo "No hay cambios para commit"
          git push origin ${{ github.ref }}

      # Subir la carpeta export como artifact
      - name: Subir artifact de export
        uses: actions/upload-artifact@v4
        with:
          name: export
          path: modelos/export
