/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.tec.carpooling.presentation.view.admin;

import javax.swing.JPanel;

/**
 *
 * @author mauricio
 */
public class AdminFrame extends javax.swing.JFrame {

    /**
     * Creates new form AdminFrame
     */
    public AdminFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelMain = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItemManagementInstitutions = new javax.swing.JMenuItem();
        jMenuItemManagementUsers = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItemManageGenres = new javax.swing.JMenuItem();
        jMenuItemManageIdentificationTypes = new javax.swing.JMenuItem();
        jMenuItemManagePhoneTypes = new javax.swing.JMenuItem();
        jMenuItemManageCurrencys = new javax.swing.JMenuItem();
        jMenuItemManageLocations = new javax.swing.JMenuItem();
        jMenuItemManageMaxCapacity = new javax.swing.JMenuItem();
        jMenuItemManagePaymentMethods = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItemParameters = new javax.swing.JMenuItem();
        jMenuItemLogs = new javax.swing.JMenuItem();
        jMenuItemStadistics = new javax.swing.JMenuItem();
        jMenuItemQuerys = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout jPanelMainLayout = new javax.swing.GroupLayout(jPanelMain);
        jPanelMain.setLayout(jPanelMainLayout);
        jPanelMainLayout.setHorizontalGroup(
            jPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 800, Short.MAX_VALUE)
        );
        jPanelMainLayout.setVerticalGroup(
            jPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 576, Short.MAX_VALUE)
        );

        jMenu1.setText("Management");

        jMenuItemManagementInstitutions.setText("Institutions");
        jMenuItemManagementInstitutions.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemManagementInstitutionsActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItemManagementInstitutions);

        jMenuItemManagementUsers.setText("Users");
        jMenuItemManagementUsers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemManagementUsersActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItemManagementUsers);

        jMenuBar1.add(jMenu1);

        jMenu3.setText("Catalogs");

        jMenuItemManageGenres.setText("Manage Genres");
        jMenuItemManageGenres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemManageGenresActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItemManageGenres);

        jMenuItemManageIdentificationTypes.setText("Manage ID Types");
        jMenuItemManageIdentificationTypes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemManageIdentificationTypesActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItemManageIdentificationTypes);

        jMenuItemManagePhoneTypes.setText("Manage Phone Types");
        jMenuItemManagePhoneTypes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemManagePhoneTypesActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItemManagePhoneTypes);

        jMenuItemManageCurrencys.setText("Manage Currencys");
        jMenuItemManageCurrencys.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemManageCurrencysActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItemManageCurrencys);

        jMenuItemManageLocations.setText("Manage Locations");
        jMenuItemManageLocations.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemManageLocationsActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItemManageLocations);

        jMenuItemManageMaxCapacity.setText("Manage Max Capacity");
        jMenuItemManageMaxCapacity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemManageMaxCapacityActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItemManageMaxCapacity);

        jMenuItemManagePaymentMethods.setText("Manage Payment Methods");
        jMenuItemManagePaymentMethods.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemManagePaymentMethodsActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItemManagePaymentMethods);

        jMenuBar1.add(jMenu3);

        jMenu2.setText("System");

        jMenuItemParameters.setText("Parameters");
        jMenuItemParameters.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemParametersActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItemParameters);

        jMenuItemLogs.setText("Logs");
        jMenuItemLogs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemLogsActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItemLogs);

        jMenuItemStadistics.setText("Stadistics");
        jMenu2.add(jMenuItemStadistics);

        jMenuItemQuerys.setText("Querys");
        jMenuItemQuerys.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemQuerysActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItemQuerys);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItemManagementInstitutionsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemManagementInstitutionsActionPerformed
        Institutions institutionsPanel = new Institutions();
        showPanel(institutionsPanel);
    }//GEN-LAST:event_jMenuItemManagementInstitutionsActionPerformed

    private void jMenuItemQuerysActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemQuerysActionPerformed
        Queries newQueryPanel = new Queries();
        showPanel(newQueryPanel);
    }//GEN-LAST:event_jMenuItemQuerysActionPerformed

    private void jMenuItemManagementUsersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemManagementUsersActionPerformed
       showPanel(new Users());
    }//GEN-LAST:event_jMenuItemManagementUsersActionPerformed

    private void jMenuItemManageIdentificationTypesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemManageIdentificationTypesActionPerformed
        showPanel(new IDTypes());
    }//GEN-LAST:event_jMenuItemManageIdentificationTypesActionPerformed

    private void jMenuItemManageGenresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemManageGenresActionPerformed
        showPanel(new Genres());
    }//GEN-LAST:event_jMenuItemManageGenresActionPerformed

    private void jMenuItemManagePhoneTypesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemManagePhoneTypesActionPerformed
        showPanel(new PhoneTypes());
    }//GEN-LAST:event_jMenuItemManagePhoneTypesActionPerformed

    private void jMenuItemManageMaxCapacityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemManageMaxCapacityActionPerformed
        showPanel(new MaxCapacity());
    }//GEN-LAST:event_jMenuItemManageMaxCapacityActionPerformed

    private void jMenuItemManageCurrencysActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemManageCurrencysActionPerformed
        showPanel(new Currency());
    }//GEN-LAST:event_jMenuItemManageCurrencysActionPerformed

    private void jMenuItemManageLocationsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemManageLocationsActionPerformed
         showPanel(new Locations());
    }//GEN-LAST:event_jMenuItemManageLocationsActionPerformed

    private void jMenuItemParametersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemParametersActionPerformed
       showPanel(new Parameters());
    }//GEN-LAST:event_jMenuItemParametersActionPerformed

    private void jMenuItemManagePaymentMethodsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemManagePaymentMethodsActionPerformed
        showPanel(new PaymentMethods());
    }//GEN-LAST:event_jMenuItemManagePaymentMethodsActionPerformed

    private void jMenuItemLogsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemLogsActionPerformed
        showPanel(new Logs());
    }//GEN-LAST:event_jMenuItemLogsActionPerformed
    
    

    private void showPanel(JPanel panel) {
        // Limpiar el panel principal
        jPanelMain.removeAll();
        
        // Configurar el layout del panel principal para centrar
        jPanelMain.setLayout(new java.awt.BorderLayout());
        
        // Crear un panel contenedor con GridBagLayout para centrar
        JPanel centerPanel = new JPanel(new java.awt.GridBagLayout());
        centerPanel.setBackground(jPanelMain.getBackground());
        
        // Agregar el panel al centro
        centerPanel.add(panel);
        
        // Agregar el panel centrado al panel principal
        jPanelMain.add(centerPanel, java.awt.BorderLayout.CENTER);
        
        // Actualizar la interfaz
        jPanelMain.revalidate();
        jPanelMain.repaint();
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItemLogs;
    private javax.swing.JMenuItem jMenuItemManageCurrencys;
    private javax.swing.JMenuItem jMenuItemManageGenres;
    private javax.swing.JMenuItem jMenuItemManageIdentificationTypes;
    private javax.swing.JMenuItem jMenuItemManageLocations;
    private javax.swing.JMenuItem jMenuItemManageMaxCapacity;
    private javax.swing.JMenuItem jMenuItemManagePaymentMethods;
    private javax.swing.JMenuItem jMenuItemManagePhoneTypes;
    private javax.swing.JMenuItem jMenuItemManagementInstitutions;
    private javax.swing.JMenuItem jMenuItemManagementUsers;
    private javax.swing.JMenuItem jMenuItemParameters;
    private javax.swing.JMenuItem jMenuItemQuerys;
    private javax.swing.JMenuItem jMenuItemStadistics;
    private javax.swing.JPanel jPanelMain;
    // End of variables declaration//GEN-END:variables
}
