package com.tec.carpooling.presentation.view.admin;

import com.tec.carpooling.business.service.InstitutionService;
import com.tec.carpooling.business.service.impl.InstitutionServiceImpl;
import com.tec.carpooling.dto.InstitutionDTO;
import com.tec.carpooling.exception.InstitutionManagementException;
import java.awt.Frame;
import java.awt.event.MouseEvent;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author mauricio
 */
public class Genres extends javax.swing.JPanel {

    private final InstitutionService institutionService; // Inyectar!
    private DefaultTableModel institutionTableModel;
    private Long selectedInstitutionId = null; // Para guardar el ID seleccionado

    public Genres() {
        // --- ¡¡MEJORAR ESTO CON INYECCIÓN DE DEPENDENCIAS!! ---
        this.institutionService = new InstitutionServiceImpl();
        // ---
        initComponents();
        initTableModel();
        loadInstitutions(); // Cargar datos al iniciar
        jButtonGenresUpdate.setEnabled(false);
        jButtonGenresDelete.setEnabled(false);
    }

    private void initTableModel() {
        institutionTableModel = new DefaultTableModel(
            new Object [][] {},
            new String [] {
                "ID", "Name"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Long.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        };
        jTableGenres.setModel(institutionTableModel);
    }

    private void loadInstitutions() {
        try {
            List<InstitutionDTO> institutions = institutionService.getAllInstitutions();
            institutionTableModel.setRowCount(0); // Limpiar tabla antes de cargar
            for (InstitutionDTO inst : institutions) {
                institutionTableModel.addRow(new Object[]{inst.getId(), inst.getName()});
            }
             clearSelectionAndFields();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, 
                "Error al cargar instituciones: " + e.getMessage(), 
                "Error de Carga", 
                JOptionPane.ERROR_MESSAGE);
        }
    }
    
   private void clearSelectionAndFields() {
        jTableGenres.clearSelection();
        jTextFieldGenresName.setText("");
        selectedInstitutionId = null;
        jButtonGenresUpdate.setEnabled(false);
        jButtonGenresDelete.setEnabled(false);
        jButtonGenresSave.setEnabled(true); // Habilitar Guardar
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelGenresName = new javax.swing.JLabel();
        jTextFieldGenresName = new javax.swing.JTextField();
        jButtonGenresSave = new javax.swing.JButton();
        jButtonGenresUpdate = new javax.swing.JButton();
        jButtonGenresDelete = new javax.swing.JButton();
        jScrollPanelGenres = new javax.swing.JScrollPane();
        jTableGenres = new javax.swing.JTable();

        setPreferredSize(new java.awt.Dimension(800, 600));

        jLabelGenresName.setText("Name");

        jTextFieldGenresName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldGenresNameActionPerformed(evt);
            }
        });

        jButtonGenresSave.setText("Save");
        jButtonGenresSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGenresSaveActionPerformed(evt);
            }
        });

        jButtonGenresUpdate.setText("Update");
        jButtonGenresUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGenresUpdateActionPerformed(evt);
            }
        });

        jButtonGenresDelete.setText("Delete");
        jButtonGenresDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGenresDeleteActionPerformed(evt);
            }
        });

        jTableGenres.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Name"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Long.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableGenres.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableGenresMouseClicked(evt);
            }
        });
        jScrollPanelGenres.setViewportView(jTableGenres);
        if (jTableGenres.getColumnModel().getColumnCount() > 0) {
            jTableGenres.getColumnModel().getColumn(0).setPreferredWidth(50);
            jTableGenres.getColumnModel().getColumn(1).setPreferredWidth(200);
        }

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(107, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jButtonGenresUpdate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonGenresDelete, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonGenresSave))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPanelGenres, javax.swing.GroupLayout.PREFERRED_SIZE, 564, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabelGenresName)
                                .addGap(38, 38, 38)
                                .addComponent(jTextFieldGenresName, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(26, 26, 26)))
                .addGap(103, 103, 103))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(105, 105, 105)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButtonGenresSave)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonGenresUpdate)
                        .addGap(12, 12, 12)
                        .addComponent(jButtonGenresDelete))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(jLabelGenresName))
                            .addComponent(jTextFieldGenresName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(48, 48, 48)
                .addComponent(jScrollPanelGenres, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(140, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldGenresNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldGenresNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldGenresNameActionPerformed

    private void jButtonGenresSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGenresSaveActionPerformed
        String name = jTextFieldGenresName.getText().trim();
        if (name.isEmpty()) {
            JOptionPane.showMessageDialog(this, "El nombre de la institución no puede estar vacío.", "Entrada Inválida", JOptionPane.WARNING_MESSAGE);
            return;
        }

        try {
            InstitutionDTO newInstitution = institutionService.registerInstitution(name);
            JOptionPane.showMessageDialog(this, "Institución '" + newInstitution.getName() + "' registrada con ID: " + newInstitution.getId());
            loadInstitutions(); // Recargar la tabla
        } catch (InstitutionManagementException e) {
             JOptionPane.showMessageDialog(this, "Error al guardar: " + e.getMessage(), "Error de Registro", JOptionPane.WARNING_MESSAGE);
        } catch (Exception e) {
            // Loggear
             JOptionPane.showMessageDialog(this, "Error inesperado al guardar: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButtonGenresSaveActionPerformed

    private void jButtonGenresUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGenresUpdateActionPerformed
        if (selectedInstitutionId == null) {
             JOptionPane.showMessageDialog(this, "Por favor, seleccione una institución de la tabla para actualizar.", "Sin Selección", JOptionPane.WARNING_MESSAGE);
            return;
        }
         String newName = jTextFieldGenresName.getText().trim();
        if (newName.isEmpty()) {
            JOptionPane.showMessageDialog(this, "El nombre de la institución no puede estar vacío.", "Entrada Inválida", JOptionPane.WARNING_MESSAGE);
            return;
        }

        try {
            boolean success = institutionService.updateInstitutionName(selectedInstitutionId, newName);
             if (success) {
                JOptionPane.showMessageDialog(this, "Nombre de la institución actualizado.");
                loadInstitutions(); // Recargar tabla
            }
            // El servicio debería lanzar excepción si falla
        } catch (InstitutionManagementException e) {
             JOptionPane.showMessageDialog(this, "Error al actualizar: " + e.getMessage(), "Error de Actualización", JOptionPane.WARNING_MESSAGE);
        } catch (Exception e) {
             // Loggear
             JOptionPane.showMessageDialog(this, "Error inesperado al actualizar: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_jButtonGenresUpdateActionPerformed

    private void jButtonGenresDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGenresDeleteActionPerformed
        if (selectedInstitutionId == null) {
             JOptionPane.showMessageDialog(this, "Por favor, seleccione una institución de la tabla para eliminar.", "Sin Selección", JOptionPane.WARNING_MESSAGE);
            return;
        }

        int confirmation = JOptionPane.showConfirmDialog(this,
                "¿Está seguro de que desea eliminar la institución seleccionada?\n(ID: " + selectedInstitutionId + " - Nombre: " + jTextFieldGenresName.getText() + ")\n¡Esta acción no se puede deshacer!",
                "Confirmar Eliminación",
                JOptionPane.YES_NO_OPTION,
                JOptionPane.WARNING_MESSAGE);

        if (confirmation == JOptionPane.YES_OPTION) {
             try {
                boolean success = institutionService.deleteInstitution(selectedInstitutionId);
                 if (success) {
                    JOptionPane.showMessageDialog(this, "Institución eliminada.");
                    loadInstitutions(); // Recargar tabla
                }
                // El servicio debería lanzar excepción si falla
            } catch (InstitutionManagementException e) { // Capturar error específico si existe FK constraint
                 JOptionPane.showMessageDialog(this, "Error al eliminar: " + e.getMessage() + "\n(Posiblemente está asociada a usuarios u otros datos).", "Error de Eliminación", JOptionPane.WARNING_MESSAGE);
            }
             catch (Exception e) {
                 // Loggear
                 JOptionPane.showMessageDialog(this, "Error inesperado al eliminar: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_jButtonGenresDeleteActionPerformed

    private void jTableGenresMouseClicked(java.awt.event.MouseEvent evt) {
       int selectedRow = jTableGenres.getSelectedRow();
       if (selectedRow >= 0) {
           selectedInstitutionId = (Long) institutionTableModel.getValueAt(selectedRow, 0);
           String selectedName = (String) institutionTableModel.getValueAt(selectedRow, 1);

           jTextFieldGenresName.setText(selectedName);

            jButtonGenresSave.setEnabled(false);
           jButtonGenresUpdate.setEnabled(true);
           jButtonGenresDelete.setEnabled(true);
       } else {
            clearSelectionAndFields();
        }
       }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonGenresDelete;
    private javax.swing.JButton jButtonGenresSave;
    private javax.swing.JButton jButtonGenresUpdate;
    private javax.swing.JLabel jLabelGenresName;
    private javax.swing.JScrollPane jScrollPanelGenres;
    private javax.swing.JTable jTableGenres;
    private javax.swing.JTextField jTextFieldGenresName;
    // End of variables declaration//GEN-END:variables
}
