/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.tec.carpooling.presentation.view.admin;

import java.sql.CallableStatement;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import javax.swing.table.DefaultTableModel;
import com.tec.carpooling.data.connection.DatabaseConnection;
import oracle.jdbc.OracleTypes;

/**
 *
 * @author mauricio
 */
public class IDTypes extends javax.swing.JPanel {

    private DefaultTableModel idTypeTableModel;
    private Long selectedIdTypeId = null;

    public IDTypes() {
        initComponents();
        initTableModel();
        loadIdTypes();
        jButtonIDTypeUpdate.setEnabled(false);
        jButtonIDTypeDelete.setEnabled(false);
    }

    private void initTableModel() {
        idTypeTableModel = new DefaultTableModel(
            new Object [][] {},
            new String [] {
                "ID", "Name"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Long.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        };
        jTableInstitution.setModel(idTypeTableModel);
    }

    private void loadIdTypes() {
        try (Connection conn = DatabaseConnection.getConnection();
             CallableStatement cstmt = conn.prepareCall("{ call ADM.LIST_TYPE_IDENTIFICATIONS(?) }")) {
            
            cstmt.registerOutParameter(1, OracleTypes.CURSOR);
            cstmt.execute();
            
            try (ResultSet rs = (ResultSet) cstmt.getObject(1)) {
                idTypeTableModel.setRowCount(0);
                while (rs.next()) {
                    idTypeTableModel.addRow(new Object[]{
                        rs.getLong("id"),
                        rs.getString("name")
                    });
                }
            }
             clearSelectionAndFields();
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, 
                "Error loading identification types: " + e.getMessage(), 
                "Load Error", 
                JOptionPane.ERROR_MESSAGE);
        }
    }
    
   private void clearSelectionAndFields() {
        jTableInstitution.clearSelection();
        jTextFieldIDTypesName.setText("");
        selectedIdTypeId = null;
        jButtonIDTypeUpdate.setEnabled(false);
        jButtonIDTypeDelete.setEnabled(false);
        jButtonIDTypeSave.setEnabled(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelInstitutionName = new javax.swing.JLabel();
        jTextFieldIDTypesName = new javax.swing.JTextField();
        jButtonIDTypeSave = new javax.swing.JButton();
        jButtonIDTypeUpdate = new javax.swing.JButton();
        jButtonIDTypeDelete = new javax.swing.JButton();
        jScrollPaneInstitution = new javax.swing.JScrollPane();
        jTableInstitution = new javax.swing.JTable();

        setPreferredSize(new java.awt.Dimension(800, 600));

        jLabelInstitutionName.setText("Name");

        jTextFieldIDTypesName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldIDTypesNameActionPerformed(evt);
            }
        });

        jButtonIDTypeSave.setText("Save");
        jButtonIDTypeSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonIDTypeSaveActionPerformed(evt);
            }
        });

        jButtonIDTypeUpdate.setText("Update");
        jButtonIDTypeUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonIDTypeUpdateActionPerformed(evt);
            }
        });

        jButtonIDTypeDelete.setText("Delete");
        jButtonIDTypeDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonIDTypeDeleteActionPerformed(evt);
            }
        });

        jTableInstitution.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Name"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Long.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableInstitution.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableInstitutionMouseClicked(evt);
            }
        });
        jScrollPaneInstitution.setViewportView(jTableInstitution);
        if (jTableInstitution.getColumnModel().getColumnCount() > 0) {
            jTableInstitution.getColumnModel().getColumn(0).setPreferredWidth(50);
            jTableInstitution.getColumnModel().getColumn(1).setPreferredWidth(200);
        }

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(107, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jButtonIDTypeUpdate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonIDTypeDelete, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonIDTypeSave))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPaneInstitution, javax.swing.GroupLayout.PREFERRED_SIZE, 564, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabelInstitutionName)
                                .addGap(38, 38, 38)
                                .addComponent(jTextFieldIDTypesName, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(26, 26, 26)))
                .addGap(103, 103, 103))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(105, 105, 105)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButtonIDTypeSave)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonIDTypeUpdate)
                        .addGap(12, 12, 12)
                        .addComponent(jButtonIDTypeDelete))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(jLabelInstitutionName))
                            .addComponent(jTextFieldIDTypesName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(48, 48, 48)
                .addComponent(jScrollPaneInstitution, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(140, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldIDTypesNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldIDTypesNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldIDTypesNameActionPerformed

    private void jButtonIDTypeSaveActionPerformed(java.awt.event.ActionEvent evt) {
        String name = jTextFieldIDTypesName.getText().trim();
        if (name.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Identification type name cannot be empty.", "Invalid Input", JOptionPane.WARNING_MESSAGE);
            return;
        }

        try (Connection conn = DatabaseConnection.getConnection();
             CallableStatement cstmt = conn.prepareCall("{ call ADM.INSERT_TYPE_IDENTIFICATION(?) }")) {
            
            cstmt.setString(1, name);
            cstmt.execute();
            
            JOptionPane.showMessageDialog(this, "Identification type '" + name + "' registered successfully.");
            loadIdTypes();
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, 
                "Error saving identification type: " + e.getMessage(), 
                "Save Error", 
                JOptionPane.ERROR_MESSAGE);
        }
    }

    private void jButtonIDTypeUpdateActionPerformed(java.awt.event.ActionEvent evt) {
        if (selectedIdTypeId == null) {
            JOptionPane.showMessageDialog(this, "Please select an identification type from the table to update.", "No Selection", JOptionPane.WARNING_MESSAGE);
            return;
        }

         String newName = jTextFieldIDTypesName.getText().trim();
        if (newName.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Identification type name cannot be empty.", "Invalid Input", JOptionPane.WARNING_MESSAGE);
            return;
        }

        try (Connection conn = DatabaseConnection.getConnection();
             CallableStatement cstmt = conn.prepareCall("{ call ADM.UPDATE_TYPE_IDENTIFICATION(?, ?) }")) {
            
            cstmt.setLong(1, selectedIdTypeId);
            cstmt.setString(2, newName);
            cstmt.execute();
            
            JOptionPane.showMessageDialog(this, "Identification type updated successfully.");
            loadIdTypes();
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, 
                "Error updating identification type: " + e.getMessage(), 
                "Update Error", 
                JOptionPane.ERROR_MESSAGE);
        }
    }

    private void jButtonIDTypeDeleteActionPerformed(java.awt.event.ActionEvent evt) {
        if (selectedIdTypeId == null) {
            JOptionPane.showMessageDialog(this, "Please select an identification type from the table to delete.", "No Selection", JOptionPane.WARNING_MESSAGE);
            return;
        }

        int confirmation = JOptionPane.showConfirmDialog(this,
                "Are you sure you want to delete the selected identification type?\n(ID: " + selectedIdTypeId + " - Name: " + jTextFieldIDTypesName.getText() + ")\nThis action cannot be undone!",
                "Confirm Deletion",
                JOptionPane.YES_NO_OPTION,
                JOptionPane.WARNING_MESSAGE);

        if (confirmation == JOptionPane.YES_OPTION) {
            try (Connection conn = DatabaseConnection.getConnection();
                 CallableStatement cstmt = conn.prepareCall("{ call ADM.DELETE_TYPE_IDENTIFICATION(?) }")) {
                
                cstmt.setLong(1, selectedIdTypeId);
                cstmt.execute();
                
                JOptionPane.showMessageDialog(this, "Identification type deleted successfully.");
                loadIdTypes();
            } catch (SQLException e) {
                JOptionPane.showMessageDialog(this, 
                    "Error deleting identification type: " + e.getMessage() + "\n(Possibly associated with persons or other data).", 
                    "Delete Error", 
                    JOptionPane.ERROR_MESSAGE);
            }
        }
    }

    private void jTableInstitutionMouseClicked(java.awt.event.MouseEvent evt) {
       int selectedRow = jTableInstitution.getSelectedRow();
       if (selectedRow >= 0) {
            selectedIdTypeId = (Long) idTypeTableModel.getValueAt(selectedRow, 0);
            String selectedName = (String) idTypeTableModel.getValueAt(selectedRow, 1);

           jTextFieldIDTypesName.setText(selectedName);

            jButtonIDTypeSave.setEnabled(false);
           jButtonIDTypeUpdate.setEnabled(true);
           jButtonIDTypeDelete.setEnabled(true);
       } else {
            clearSelectionAndFields();
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonIDTypeDelete;
    private javax.swing.JButton jButtonIDTypeSave;
    private javax.swing.JButton jButtonIDTypeUpdate;
    private javax.swing.JLabel jLabelInstitutionName;
    private javax.swing.JScrollPane jScrollPaneInstitution;
    private javax.swing.JTable jTableInstitution;
    private javax.swing.JTextField jTextFieldIDTypesName;
    // End of variables declaration//GEN-END:variables
}
