/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.tec.carpooling.presentation.view.admin;

import com.tec.carpooling.business.service.InstitutionService;
import com.tec.carpooling.business.service.impl.InstitutionServiceImpl;
import com.tec.carpooling.dto.InstitutionDTO;
import com.tec.carpooling.exception.InstitutionManagementException;
import java.awt.Frame;
import java.sql.CallableStatement;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author mauricio
 */
public class Institutions extends javax.swing.JPanel {

    private final InstitutionService institutionService; // Inyectar!
    private DefaultTableModel institutionTableModel;
    private Long selectedInstitutionId = null; // Para guardar el ID seleccionado

    public Institutions() {
        // --- ¡¡MEJORAR ESTO CON INYECCIÓN DE DEPENDENCIAS!! ---
        this.institutionService = new InstitutionServiceImpl();
        // ---
        initComponents();
        initTableModel();
        loadInstitutions(); // Cargar datos al iniciar
        jButtonEditDomains.setEnabled(false); // Deshabilitar hasta seleccionar
        jButtonInstitutionUpdate.setEnabled(false);
        jButtonInstitutionDelete.setEnabled(false);
    }

    private void initTableModel() {
        institutionTableModel = new DefaultTableModel(
            new Object [][] {},
            new String [] {
                "ID", "Name"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Long.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        };
        jTableInstitution.setModel(institutionTableModel);
    }

    private void loadInstitutions() {
        try (Connection conn = com.tec.carpooling.data.connection.DatabaseConnection.getConnection();
             CallableStatement stmt = conn.prepareCall("CALL find_all_institutions()")) {
            ResultSet rs = stmt.executeQuery();
            institutionTableModel.setRowCount(0);
            while (rs.next()) {
                institutionTableModel.addRow(new Object[]{rs.getLong("id"), rs.getString("name")});
            }
             clearSelectionAndFields();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, 
                "Error al cargar instituciones: " + e.getMessage(), 
                "Error de Carga", 
                JOptionPane.ERROR_MESSAGE);
        }
    }
    
   private void clearSelectionAndFields() {
        jTableInstitution.clearSelection();
        jTextFieldInstitutionName.setText("");
        selectedInstitutionId = null;
        jButtonEditDomains.setEnabled(false);
        jButtonInstitutionUpdate.setEnabled(false);
        jButtonInstitutionDelete.setEnabled(false);
        jButtonInstitutionSave.setEnabled(true); // Habilitar Guardar
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelInstitutionName = new javax.swing.JLabel();
        jTextFieldInstitutionName = new javax.swing.JTextField();
        jButtonInstitutionSave = new javax.swing.JButton();
        jButtonInstitutionUpdate = new javax.swing.JButton();
        jButtonInstitutionDelete = new javax.swing.JButton();
        jScrollPaneInstitution = new javax.swing.JScrollPane();
        jTableInstitution = new javax.swing.JTable();
        jLabelInstitutionDomains = new javax.swing.JLabel();
        jButtonEditDomains = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(800, 600));

        jLabelInstitutionName.setText("Name");

        jTextFieldInstitutionName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldInstitutionNameActionPerformed(evt);
            }
        });

        jButtonInstitutionSave.setText("Save");
        jButtonInstitutionSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonInstitutionSaveActionPerformed(evt);
            }
        });

        jButtonInstitutionUpdate.setText("Update");
        jButtonInstitutionUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonInstitutionUpdateActionPerformed(evt);
            }
        });

        jButtonInstitutionDelete.setText("Delete");
        jButtonInstitutionDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonInstitutionDeleteActionPerformed(evt);
            }
        });

        jTableInstitution.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Name"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableInstitution.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableInstitutionMouseClicked(evt);
            }
        });
        jScrollPaneInstitution.setViewportView(jTableInstitution);

        jLabelInstitutionDomains.setText("Domains");

        jButtonEditDomains.setText("See/Change");
        jButtonEditDomains.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEditDomainsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(107, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jButtonInstitutionUpdate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonInstitutionDelete, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonInstitutionSave))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPaneInstitution, javax.swing.GroupLayout.PREFERRED_SIZE, 564, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelInstitutionName)
                                    .addComponent(jLabelInstitutionDomains, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButtonEditDomains, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextFieldInstitutionName, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(26, 26, 26)))
                .addGap(103, 103, 103))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(105, 105, 105)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButtonInstitutionSave)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonInstitutionUpdate)
                        .addGap(12, 12, 12)
                        .addComponent(jButtonInstitutionDelete))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(jLabelInstitutionName))
                            .addComponent(jTextFieldInstitutionName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButtonEditDomains)
                            .addComponent(jLabelInstitutionDomains))))
                .addGap(48, 48, 48)
                .addComponent(jScrollPaneInstitution, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(140, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldInstitutionNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldInstitutionNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldInstitutionNameActionPerformed

    private void jButtonInstitutionSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonInstitutionSaveActionPerformed
        String name = jTextFieldInstitutionName.getText().trim();
        if (name.isEmpty()) {
            JOptionPane.showMessageDialog(this, "El nombre de la institución no puede estar vacío.", "Entrada Inválida", JOptionPane.WARNING_MESSAGE);
            return;
        }

        try (Connection conn = com.tec.carpooling.data.connection.DatabaseConnection.getConnection();
             CallableStatement stmt = conn.prepareCall("CALL create_institution(?, ?)")) {
            stmt.setString(1, name);
            stmt.registerOutParameter(2, java.sql.Types.INTEGER);
            stmt.execute();
            int newId = stmt.getInt(2);
            JOptionPane.showMessageDialog(this, "Institución '" + name + "' registrada con ID: " + newId);
            loadInstitutions();
        } catch (SQLException e) {
            String msg = e.getMessage();
            if (msg.contains("already exists")) {
                JOptionPane.showMessageDialog(this, "La institución ya existe.", "Error de Registro", JOptionPane.WARNING_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(this, "Error inesperado al guardar: " + msg, "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_jButtonInstitutionSaveActionPerformed

    private void jButtonInstitutionUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonInstitutionUpdateActionPerformed
        if (selectedInstitutionId == null) {
             JOptionPane.showMessageDialog(this, "Por favor, seleccione una institución de la tabla para actualizar.", "Sin Selección", JOptionPane.WARNING_MESSAGE);
            return;
        }
         String newName = jTextFieldInstitutionName.getText().trim();
        if (newName.isEmpty()) {
            JOptionPane.showMessageDialog(this, "El nombre de la institución no puede estar vacío.", "Entrada Inválida", JOptionPane.WARNING_MESSAGE);
            return;
        }

        try (Connection conn = com.tec.carpooling.data.connection.DatabaseConnection.getConnection();
             CallableStatement stmt = conn.prepareCall("CALL update_institution_name(?, ?)")) {
            stmt.setLong(1, selectedInstitutionId);
            stmt.setString(2, newName);
            stmt.execute();
                JOptionPane.showMessageDialog(this, "Nombre de la institución actualizado.");
            loadInstitutions();
        } catch (SQLException e) {
            String msg = e.getMessage();
            if (msg.contains("already in use")) {
                JOptionPane.showMessageDialog(this, "El nombre ya está en uso.", "Error de Actualización", JOptionPane.WARNING_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(this, "Error inesperado al actualizar: " + msg, "Error", JOptionPane.ERROR_MESSAGE);
            }
        }

    }//GEN-LAST:event_jButtonInstitutionUpdateActionPerformed

    private void jButtonInstitutionDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonInstitutionDeleteActionPerformed
        if (selectedInstitutionId == null) {
             JOptionPane.showMessageDialog(this, "Por favor, seleccione una institución de la tabla para eliminar.", "Sin Selección", JOptionPane.WARNING_MESSAGE);
            return;
        }

        try (Connection conn = com.tec.carpooling.data.connection.DatabaseConnection.getConnection();
             CallableStatement stmt = conn.prepareCall("CALL delete_institution(?)")) {
            stmt.setLong(1, selectedInstitutionId);
            stmt.execute();
                    JOptionPane.showMessageDialog(this, "Institución eliminada.");
            loadInstitutions();
        } catch (SQLException e) {
            String msg = e.getMessage();
            if (msg.contains("associated with users")) {
                JOptionPane.showMessageDialog(this, "No se puede eliminar la institución porque está asociada a usuarios u otros datos.", "Error de Eliminación", JOptionPane.WARNING_MESSAGE);
            } else if (msg.contains("not found")) {
                JOptionPane.showMessageDialog(this, "No se encontró la institución.", "Error de Eliminación", JOptionPane.WARNING_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(this, "Error inesperado al eliminar: " + msg, "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_jButtonInstitutionDeleteActionPerformed

    private void jTableInstitutionMouseClicked(java.awt.event.MouseEvent evt) {
       int selectedRow = jTableInstitution.getSelectedRow();
       if (selectedRow >= 0) {
           selectedInstitutionId = (Long) institutionTableModel.getValueAt(selectedRow, 0);
           String selectedName = (String) institutionTableModel.getValueAt(selectedRow, 1);

           jTextFieldInstitutionName.setText(selectedName);

            jButtonInstitutionSave.setEnabled(false);
           jButtonInstitutionUpdate.setEnabled(true);
           jButtonInstitutionDelete.setEnabled(true);
           jButtonEditDomains.setEnabled(true);
       } else {
            clearSelectionAndFields();
        }
       }

    private void jButtonEditDomainsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEditDomainsActionPerformed
        editDomainsButtonActionPerformed(evt);

        // El diálogo se encarga de guardar los cambios, no necesitamos hacer nada aquí después de que cierre.
        // Si necesitaras refrescar algo en ESTE panel después de que el diálogo cierre,
        // podrías añadir un listener al diálogo o hacer que devuelva un valor.
    }//GEN-LAST:event_jButtonEditDomainsActionPerformed

    private void editDomainsButtonActionPerformed(java.awt.event.ActionEvent evt) {
        if (selectedInstitutionId == null) {
            JOptionPane.showMessageDialog(this,
                "Por favor seleccione una institución primero.",
                "Sin Selección",
                JOptionPane.WARNING_MESSAGE);
            return;
        }

        javax.swing.JFrame parentFrame = (javax.swing.JFrame) SwingUtilities.getWindowAncestor(this);
        Domains domainsDialog = new Domains(parentFrame, true, selectedInstitutionId.intValue(), jTextFieldInstitutionName.getText());
        domainsDialog.setVisible(true);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonEditDomains;
    private javax.swing.JButton jButtonInstitutionDelete;
    private javax.swing.JButton jButtonInstitutionSave;
    private javax.swing.JButton jButtonInstitutionUpdate;
    private javax.swing.JLabel jLabelInstitutionDomains;
    private javax.swing.JLabel jLabelInstitutionName;
    private javax.swing.JScrollPane jScrollPaneInstitution;
    private javax.swing.JTable jTableInstitution;
    private javax.swing.JTextField jTextFieldInstitutionName;
    // End of variables declaration//GEN-END:variables
}
